---

- name: Get outdated grafana versions in filesystem.
  shell: ls {{ grafana_home }} | grep grafana | grep -v tar | head -n -1
  register: grafana_outdated_versions

- name: Delete outdated grafana versions from filesystem.
  file:
    path: "{{ grafana_home }}/{{ item }}"
    state: absent

    