---
- hosts: all
  roles:
  - roles/prometheus
  - roles/alertmanager
  - roles/pushgateway
  - roles/node-exporter
  - roles/elasticsearch-exporter
  #- roles/netdata
  - roles/grafana
  #- roles/jmx_prometheus_javaagent


