{
 "title": "HDFS - Home",
 "tags": [
  "prometheus",
  "hdfs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(Hadoop_NameNode_FilesTotal, cluster)"
   },
   {
    "name": "server",
    "query": "label_values(Hadoop_NameNode_FilesTotal{cluster=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Files Under Construction & RPC Client Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Files Under Construction",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "namenode",
       "downsampleAggregator": "avg",
       "expr": "Hadoop_NameNode_NumFilesUnderConstruction{instance=~\"$server.*\", cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "none"
      }
     ]
    },
    {
     "title": "RPC Client Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "namenode",
       "downsampleAggregator": "avg",
       "expr": "Hadoop_NameNode_num_open_connections{instance=~\"$server.*\", cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "Total File Operations & Capacity Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total File Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "namenode",
       "downsampleAggregator": "avg",
       "expr": "increase(Hadoop_NameNode_TotalFileOps{instance=~\"$server.*\", cluster=\"$cluster\"}[1m])",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Capacity Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "namenode",
       "downsampleAggregator": "avg",
       "expr": "Hadoop_NameNode_CapacityUsedGB{instance=~\"$server.*\", cluster=\"$cluster\"}",
       "legendFormat": "CapacityUsedGB",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "none"
      },
      {
       "aggregator": "avg",
       "app": "namenode",
       "downsampleAggregator": "avg",
       "expr": "Hadoop_NameNode_CapacityTotalGB{instance=~\"$server.*\", cluster=\"$cluster\"}",
       "legendFormat": "CapacityTotalGB",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC Client Port Slow Calls & HDFS Total Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Client Port Slow Calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "namenode",
       "downsampleAggregator": "avg",
       "expr": "Hadoop_NameNode_rpc_slow_calls{instance=~\"$server.*\", cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "none"
      }
     ]
    },
    {
     "title": "HDFS Total Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "namenode",
       "downsampleAggregator": "avg",
       "expr": "Hadoop_NameNode_TotalLoad{instance=~\"$server.*\", cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "none"
      }
     ]
    }
   ]
  },
  { "title": "Add Block Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Add Block Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "Hadoop_NameNode_add_block_avg_time{instance=~\"$server.*\", cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}",
     "precision": "default",
     "templatedHost": "sandbox-hdp.hortonworks.com",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Add Block Num Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "downsampleAggregator": "avg",
     "expr": "Hadoop_NameNode_add_block_num_ops{instance=~\"$server.*\", cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}",
     "precision": "default",
     "templatedHost": "sandbox-hdp.hortonworks.com",
     "transform": "rate"
    }
   ]
  }
 ]
}