{
 "title": "HDFS - DataNodes",
 "tags": [
  "prometheus",
  "hdfs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(hadoop_DataNode_data_port, cluster)"
   },
   {
    "name": "server",
    "query": "label_values(hadoop_DataNode_data_port{cluster=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Blocks Written / Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocks Written",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "expr": "rate(hadoop_DataNode_blocks_written{instance=~\"$server.*\", cluster=~\"$cluster\"}[1m])",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Blocks Read",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "expr": "rate(hadoop_DataNode_blocks_read{instance=~\"$server.*\", cluster=~\"$cluster\"}[1m])",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Fsync Time / Num Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fsync Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "expr": "avg(hadoop_DataNode_fsync_nanos_avg_time{instance=~\"$server.*\", cluster=~\"$cluster\"})",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Fsync Num Ops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "expr": "avg(hadoop_DataNode_fsync_nanos_num_ops{instance=~\"$server.*\", cluster=~\"$cluster\"})",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Packets Blocked / Num Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Packet Blocked Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "expr": "hadoop_DataNode_send_data_packet_blocked_on_network_nanos_avg_time{instance=~\"$server.*\", cluster=~\"$cluster\"}",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Data Packet Blocked Num Ops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "expr": "hadoop_DataNode_send_data_packet_blocked_on_network_nanos_num_ops{instance=~\"$server.*\", cluster=~\"$cluster\"}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Packet Transfer Blocked / Num Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packet Transfer Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "expr": "hadoop_DataNode_send_data_packet_transfer_nanos_avg_time{instance=~\"$server.*\", cluster=~\"$cluster\"}",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Packet Transfer Num Ops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "expr": "hadoop_DataNode_send_data_packet_transfer_nanos_num_ops{instance=~\"$server.*\", cluster=~\"$cluster\"}",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Packet Round Trip",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packet Ack Round Trip Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "PacketAckRoundTripTime",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "expr": "hadoop_DataNode_packet_ack_round_trip_time_nanos_avg_time{instance=~\"$server.*\", cluster=~\"$cluster\"}",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "none"
      }
     ]
    },
    {
     "title": "Packet Round Trip Num Ops",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "PacketAckRoundTripNumOps",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "expr": "hadoop_DataNode_packet_ack_round_trip_time_nanos_num_ops{instance=~\"$server.*\", cluster=~\"$cluster\"}",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "diff"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Errors / GC Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "expr": "hadoop_DataNode_datanode_network_errors{instance=~\"$server.*\", cluster=~\"$cluster\"}",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "datanode",
       "downsampleAggregator": "avg",
       "expr": "irate(hadoop_DataNode_gc_count{instance=~\"$server.*\", cluster=~\"$cluster\"}[1m])",
       "legendFormat": "{{ instance }}",
       "precision": "default",
       "templatedHost": "sandbox-hdp.hortonworks.com",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  { "title": "GC Time / GC Time ParNew", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "expr": "increase(hadoop_DataNode_gc_time_millis{instance=~\"$server.*\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{ instance }}",
     "precision": "default",
     "templatedHost": "sandbox-hdp.hortonworks.com",
     "transform": "rate"
    }
   ]
  },
  {
   "title": "GC Time ParNew",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "downsampleAggregator": "avg",
     "expr": "increase(hadoop_DataNode_gc_time_millis_par_new{instance=~\"$server.*\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{ instance }}",
     "precision": "default",
     "templatedHost": "sandbox-hdp.hortonworks.com",
     "transform": "rate"
    }
   ]
  }
 ]
}