{
 "title": "HDFS NameNode Overview",
 "tags": [
  "hdfs",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(Hadoop_NameNode_FilesTotal, cluster)"
   },
   {
    "name": "server",
    "query": "label_values(Hadoop_NameNode_FilesTotal{cluster=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "HDFS Namenode Heap Used",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"namenode\",instance=~\"$server.*\", cluster=\"$cluster\", area=\"heap\"}",
     "legendFormat": "{{ instance }} used",
     "target": "aliasByNode(Hadoop.NameNode.*.Hadoop.NameNode.JvmMetrics.MemHeapUsedM.upper, 2)"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"namenode\",instance=~\"$server.*\", cluster=\"$cluster\", area=\"heap\"}",
     "legendFormat": "{{ instance }} max"
    }
   ]
  },
  {
   "title": "HDFS  Namenode GC Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"namenode\",instance=~\"$server.*\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} {{ gc }}",
     "target": "aliasByNode(nonNegativeDerivative(Hadoop.NameNode.*.Hadoop.NameNode.JvmMetrics.GcTimeMillisPSScavenge.upper), 2)"
    }
   ]
  },
  {
   "title": "HDFS  Namenode GC Counts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{job=\"namenode\",instance=~\"$server.*\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }} {{ gc }}",
     "target": "aliasByNode(nonNegativeDerivative(Hadoop.NameNode.*.Hadoop.NameNode.JvmMetrics.GcCountPSScavenge.upper), 2)"
    }
   ]
  },
  {
   "title": "HDFS Active Namenode pools",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=\"namenode\",instance=~\"$server.*\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} {{ pool }}",
     "target": "aliasByNode(Hadoop.NameNode.*.Hadoop.NameNode.JvmMetrics.MemHeapUsedM.upper, 2)"
    }
   ]
  },
  {
   "title": "HDFS Available vs Used space",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_CapacityUsedGB{cluster=\"$cluster\"}",
     "legendFormat": "CapacityUsedGB"
    },
    {
     "expr": "Hadoop_NameNode_CapacityTotalGB{cluster=\"$cluster\"}",
     "legendFormat": "CapacityTotalGB"
    }
   ]
  },
  {
   "title": "HDFS Total files",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_FilesTotal{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(Hadoop.NameNode.*.Hadoop.NameNode.FSNamesystem.FilesTotal.mean, 2)"
    }
   ]
  },
  {
   "title": "HDFS Missing Blocks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_MissingBlocks{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(Hadoop.NameNode.*.Hadoop.NameNode.FSNamesystem.MissingBlocks.mean, 2)"
    }
   ]
  },
  {
   "title": "HDFS Under Replicated Blocks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_UnderReplicatedBlocks{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(Hadoop.NameNode.*.Hadoop.NameNode.FSNamesystem.UnderReplicatedBlocks.mean, 2)"
    }
   ]
  },
  {
   "title": "HDFS total load rate (I/O ops across all workers)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Hadoop_NameNode_TotalFileOps{cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(Hadoop.NameNode.*.Hadoop.NameNode.FSNamesystem.TotalLoad.mean, 2)"
    }
   ]
  },
  {
   "title": "HDFS Corrupt Blocks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_CorruptBlocks{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(Hadoop.NameNode.*.Hadoop.NameNode.FSNamesystem.CorruptBlocks.mean, 2)"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_rpc_queue_time_num_ops{kind=\"RpcActivityForPort8020\", cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HDFS Pending Replication Blocks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_PendingReplicationBlocks{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(Hadoop.NameNode.*.Hadoop.NameNode.FSNamesystem.PendingReplicationBlocks.mean, 2)"
    }
   ]
  },
  {
   "title": "Average queue time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_rpc_processing_time_avg_time{kind=\"RpcActivityForPort8020\", cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HDFS Total Load (I/O ops across all workers)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_TotalLoad{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(Hadoop.NameNode.*.Hadoop.NameNode.FSNamesystem.TotalLoad.mean, 2)"
    }
   ]
  },
  {
   "title": "Number of RPC calls",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(Hadoop_NameNode_rpc_queue_time_num_ops{kind=\"RpcActivityForPort8020\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Current length of the call queue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_call_queue_length{kind=\"RpcActivityForPort8020\", cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Received bytes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(Hadoop_NameNode_received_bytes{kind=\"RpcActivityForPort8020\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Sent bytes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(Hadoop_NameNode_sent_bytes{kind=\"RpcActivityForPort8020\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}