{
 "title": "HDFS Journal Node Overview",
 "tags": [
  "hdfs",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(Hadoop_NameNode_FilesTotal, cluster)"
   },
   {
    "name": "server",
    "query": "label_values(Hadoop_NameNode_FilesTotal{cluster=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "HDFS Journalnode Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"journalnode\",instance=~\"$server.*\", area=\"heap\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"journalnode\",instance=~\"$server.*\", area=\"heap\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} max"
    },
    {
     "expr": "jvm_memory_bytes_committed{job=\"journalnode\",instance=~\"$server.*\", area=\"heap\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} committed"
    }
   ]
  },
  {
   "title": "HDFS Journalnode GC time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"journalnode\",instance=~\"$server.*\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} {{ gc }}"
    }
   ]
  },
  {
   "title": "HDFS Journalnode GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{job=\"journalnode\",instance=~\"$server.*\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} {{ gc }}"
    }
   ]
  },
  {
   "title": "Sync operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "sync/minute" }
   ],
   "targets": [
    {
     "expr": "Hadoop_JournalNode_Syncs60sNumOps{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sync latency (one min granularity)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "Hadoop_JournalNode_Syncs60s50thPercentileLatencyMicros{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} p50"
    },
    {
     "expr": "Hadoop_JournalNode_Syncs60s75thPercentileLatencyMicros{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} p75"
    },
    {
     "expr": "Hadoop_JournalNode_Syncs60s99thPercentileLatencyMicros{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} p99"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "transactions/s" }
   ],
   "targets": [
    {
     "expr": "rate(Hadoop_JournalNode_TxnsWritten{cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lagging transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_JournalNode_CurrentLagTxns{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_JournalNode_NumOpenConnections{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received vs Sent bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(Hadoop_JournalNode_ReceivedBytes{cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} received"
    },
    {
     "expr": "rate(Hadoop_JournalNode_SentBytes{cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} sent"
    }
   ]
  },
  {
   "title": "Sync latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "Hadoop_JournalNode_Syncs60s50thPercentileLatencyMicros{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} p50"
    },
    {
     "expr": "Hadoop_JournalNode_Syncs60s75thPercentileLatencyMicros{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} p75"
    },
    {
     "expr": "Hadoop_JournalNode_Syncs60s99thPercentileLatencyMicros{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} p99"
    }
   ]
  },
  {
   "title": "Batches written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "batches/s" }
   ],
   "targets": [
    {
     "expr": "rate(Hadoop_JournalNode_BatchesWritten{cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} received"
    }
   ]
  },
  {
   "title": "Batches written while lagging",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "batches/s" }
   ],
   "targets": [
    {
     "expr": "rate(Hadoop_JournalNode_BatchesWrittenWhileLagging{cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}} received"
    }
   ]
  },
  {
   "title": "Sync ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_JournalNode_Syncs60sNumOps{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}