{
 "title": "Kafka - Hosts",
 "tags": [
  "kafka",
  "ams"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "query": "kafka_broker" },
   { "name": "hosts", "query": "hosts" }
  ]
 },
 "panels": [
  {
   "title": "Bytes / Messages / Partitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes In & Out /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Bytes In",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.BrokerTopicMetrics.BytesInPerSec.count",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      },
      {
       "aggregator": "avg",
       "alias": "Bytes Out",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.BrokerTopicMetrics.BytesOutPerSec.count",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Messages In /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Messages In",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.BrokerTopicMetrics.MessagesInPerSec.count",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Under Replicated Partitions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Under Replicated Partitions",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.ReplicaManager.UnderReplicatedPartitions",
       "precision": "default",
       "transformData": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "Producer & Consumer Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Producer Requests /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Producer Requests",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.RequestsPerSec.request.Produce.count",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Consumer Requests /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Consumer Requests",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.RequestsPerSec.request.FetchConsumer.count",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "Replica Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Partition Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "ReplicaManager.PartitionCount",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.ReplicaManager.PartitionCount",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Leader Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "ReplicaManager.LeaderCount",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.ReplicaManager.LeaderCount",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "MaxLag Replica",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "MaxLag Replica",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.ReplicaFetcherManager.MaxLag.clientId.Replica",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "In-Sync Replica Shrinks / Expands",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "In-Sync Replica Shrinks /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "ISR Shrinks",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.ReplicaManager.IsrShrinksPerSec.count",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "In-Sync Replica Expands /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "ISR Expands",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.ReplicaManager.IsrExpandsPerSec.count",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "Replica Fetcher Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replica Fetcher Manager MaxLag",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "MaxLag",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.ReplicaFetcherManager.MaxLag.clientId.Replica",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "Fetch Consumer Total Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Time Ms (min)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "FetchConsumer (min)",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.TotalTimeMs.request.FetchConsumer.min",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Total Time ms (max)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "FetchConsumer (max)",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.TotalTimeMs.request.FetchConsumer.max",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Total Time ms (mean)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "FetchConsumer (mean)",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.TotalTimeMs.request.FetchConsumer.mean",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Total Time ms (99th Percentile)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "FetchConsumer (99th Percentile)",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.TotalTimeMs.request.FetchConsumer.99percentile",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "Fetch Follower Total Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Time ms (min)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "FetchFollower (min)",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.TotalTimeMs.request.FetchFollower.min",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Total Time ms (max)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "FetchFollower (max)",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.TotalTimeMs.request.FetchFollower.max",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Total Time ms (mean)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "FetchFollower (mean)",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.TotalTimeMs.request.FetchFollower.mean",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Total Time ms (99thPercentile)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "FetchFollower (99thPercentile)",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.TotalTimeMs.request.FetchFollower.99percentile",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "Produce Total Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Time ms (min)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Produce (min)",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.TotalTimeMs.request.Produce.min",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Total Time ms (max)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Produce (max)",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.TotalTimeMs.request.Produce.max",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Total Time ms (mean)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Produce (mean)",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.TotalTimeMs.request.Produce.mean",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Total Time ms (99th Percentile)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Produce (99th Percentile)",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.TotalTimeMs.request.Produce.99percentile",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    }
   ]
  }
 ]
}