{
 "title": "Kafka - Home",
 "tags": [
  "kafka",
  "ams"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Bytes / Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes In & Out /s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Bytes In",
     "app": "kafka_broker",
     "downsampleAggregator": "avg",
     "metric": "kafka.server.BrokerTopicMetrics.BytesInPerSec.count",
     "precision": "default",
     "transform": "none",
     "transformData": "none"
    },
    {
     "aggregator": "avg",
     "alias": "Bytes Out",
     "app": "kafka_broker",
     "downsampleAggregator": "avg",
     "metric": "kafka.server.BrokerTopicMetrics.BytesOutPerSec.count",
     "precision": "default",
     "transform": "none",
     "transformData": "none"
    }
   ]
  },
  {
   "title": "Messages In /s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Messages In",
     "app": "kafka_broker",
     "downsampleAggregator": "avg",
     "metric": "kafka.server.BrokerTopicMetrics.MessagesInPerSec.count",
     "precision": "default",
     "transform": "none",
     "transformData": "none"
    }
   ]
  },
  {
   "title": "Controller/Leader Count & Replica MaxLag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Controller Count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Active Controller Count",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.controller.KafkaController.ActiveControllerCount",
       "precision": "default",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Replica MaxLag",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Replica MaxLag",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.ReplicaFetcherManager.MaxLag.clientId.Replica",
       "precision": "default",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Leader Count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Leader Count",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.ReplicaManager.LeaderCount",
       "precision": "default",
       "transformData": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "Under Replicated Partitions & Offline Partitions Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Under Replicated Partitions",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "UnderReplicatedPartitions",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.ReplicaManager.UnderReplicatedPartitions",
       "precision": "default",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Offline Partitions Count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "aggregator": "avg",
       "alias": "OfflinePartitionsCount",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.controller.KafkaController.OfflinePartitionsCount",
       "precision": "default",
       "transformData": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "Producer & Consumer Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Produce Requests /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Produce Requests",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.RequestsPerSec.request.Produce.count",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "Consumer Requests /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Consumer Requests",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.network.RequestMetrics.RequestsPerSec.request.FetchConsumer.count",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "Leader Election & Unclean Leader Elections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Leader Election Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Leader Election Rate",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.controller.ControllerStats.LeaderElectionRateAndTimeMs.count",
       "precision": "default",
       "transform": "none",
       "transformData": "rate"
      }
     ]
    },
    {
     "title": "Unclean Leader Elections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Unclean Leader Elections",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.controller.ControllerStats.UncleanLeaderElectionsPerSec.count",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "In-Sync Replica Shrinks / Expanded",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "In-Sync Replica Shrinks /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "ISR Shrinks",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.ReplicaManager.IsrShrinksPerSec.count",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    },
    {
     "title": "In-Sync Replica Expands /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "ISR Expands",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.ReplicaManager.IsrExpandsPerSec.count",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    }
   ]
  },
  {
   "title": "Replica Fetcher Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replica Fetcher Manager MaxLag",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "aggregator": "avg",
       "alias": "MaxLag",
       "app": "kafka_broker",
       "downsampleAggregator": "avg",
       "metric": "kafka.server.ReplicaFetcherManager.MaxLag.clientId.Replica",
       "precision": "default",
       "transform": "none",
       "transformData": "none"
      }
     ]
    }
   ]
  }
 ]
}