{
 "title": "Kafka Overview",
 "tags": [
  "kafka",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(cluster)" },
   {
    "name": "kafka_broker",
    "label": "broker",
    "query": "label_values(kafka_server_KafkaServer_BrokerState{cluster=\"$cluster\"},instance)"
   },
   {
    "name": "disk_device",
    "label": "disk device",
    "query": "label_values(node_disk_reads_completed_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\",device=~\"[vs]d[a-z]+\"}, device)"
   },
   {
    "name": "topics",
    "query": "label_values(kafka_server_BrokerTopicMetrics_MessagesIn_total{cluster=\"$cluster\"}, topic)"
   }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_MessagesIn_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\", topic=\"\"} [5m]))",
     "target": "sumSeries(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.BrokerTopicMetrics-AllTopics.MessagesInPerSec.OneMinuteRate)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_BytesIn_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\", topic=\"\"} [5m]))",
     "target": "sum (irate(kafka_server_brokertopicmetrics_bytesin_total{cluster=\"$cluster\",instance=~\"$kafka_brokers\", job=\"jmx_kafka\"} [5m]))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_BytesOut_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\", topic=\"\"} [5m]))",
     "target": "sum (irate(kafka_server_brokertopicmetrics_bytesout_total{cluster=\"$cluster\",instance=~\"$kafka_brokers\", job=\"jmx_kafka\"} [5m]))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kafka_server_BrokerTopicMetrics_MessagesIn_total{cluster=\"$cluster\", topic=~\".+\"})"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_PartitionCount{cluster=\"$cluster\",instance=~\"$kafka_broker.*\"})",
     "target": "sum (irate(kafka_server_brokertopicmetrics_bytesout_total{cluster=\"$cluster\",instance=~\"$kafka_brokers\", job=\"jmx_kafka\"} [5m]))"
    }
   ]
  },
  {
   "title": "Kafka Messages In (stacked)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "messages / second" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_MessagesIn_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\",topic=\"\"} [5m])",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.BrokerTopicMetrics-AllTopics.MessagesInPerSec.OneMinuteRate, 4)"
    },
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_MessagesIn_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\",topic=\"\"} [5m]))",
     "legendFormat": "Total",
     "target": "aliasByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.BrokerTopicMetrics-AllTopics.MessagesInPerSec.OneMinuteRate, 4)"
    }
   ]
  },
  {
   "title": "Kafka Messages In",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "messages / second" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_MessagesIn_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\",topic=\"\"} [5m])",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.BrokerTopicMetrics-AllTopics.MessagesInPerSec.OneMinuteRate, 4)"
    }
   ]
  },
  {
   "title": "Kafka Bytes In (stacked)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_BytesIn_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\", topic=\"\"} [5m])",
     "legendFormat": "{{ instance }}",
     "target": "kafka_server_brokertopicmetrics_bytesin_total"
    },
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_BytesIn_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\", topic=\"\"} [5m]))",
     "legendFormat": "Total",
     "target": "kafka_server_brokertopicmetrics_bytesin_total"
    }
   ]
  },
  {
   "title": "Kafka Bytes In",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_BytesIn_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\", topic=\"\"} [5m])",
     "legendFormat": "{{ instance }}",
     "target": "kafka_server_brokertopicmetrics_bytesin_total"
    }
   ]
  },
  {
   "title": "Kafka Bytes Out (stacked)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_BytesOut_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\", topic=\"\"} [5m])",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.BrokerTopicMetrics-AllTopics.BytesOutPerSec.OneMinuteRate, 4, 8)"
    },
    {
     "expr": "sum(irate(kafka_server_BrokerTopicMetrics_BytesOut_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\", topic=\"\"} [5m]))",
     "legendFormat": "Total",
     "target": "aliasByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.BrokerTopicMetrics-AllTopics.BytesOutPerSec.OneMinuteRate, 4, 8)"
    }
   ]
  },
  {
   "title": "Kafka Bytes Out",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_BytesOut_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\", topic=\"\"} [5m])",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.BrokerTopicMetrics-AllTopics.BytesOutPerSec.OneMinuteRate, 4, 8)"
    }
   ]
  },
  {
   "title": "3 topics with highest incoming message rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "messages / second" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(3, sum(irate(kafka_server_BrokerTopicMetrics_MessagesIn_total{ instance=~\"$kafka_broker.*\", topic=~\".+\"}[5m])) by (topic)))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "3 topics with highest incoming byte rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(3, sum(irate(kafka_server_BrokerTopicMetrics_BytesIn_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\", topic=~\".+\"} [5m])) by (topic)))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Disk Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\",device=~\"$disk_device\"}[5m]) or irate(node_disk_writes_completed{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\",device=~\"$disk_device\"}[5m])",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "CPU IOwait",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu{cluster=\"$cluster\",mode=\"iowait\",instance=~\"$kafka_broker.*\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Bytes In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(irate(node_network_receive_bytes_total{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\",device=~\"(eth|eno).*\"}[5m]) and node_network_receive_bytes_total{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\",device=~\"(eth|eno).*\"} > 0) or (irate(node_network_receive_bytes{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\",device=~\"(eth|eno).*\"}[5m]) and node_network_receive_bytes{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\",device=~\"(eth|eno).*\"} > 0)",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\",device=~\"$disk_device\"}[5m]) or irate(node_disk_reads_completed{cluster=\"$cluster\",instance=~\"$kafka_broker.*\",device=~\"$disk_device\"}[5m])",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "TCP Connections ESTABLISHED",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Bytes Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(irate(node_network_transmit_bytes_total{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\",device=~\"(eth|eno).*\"} [5m]) and node_network_transmit_bytes_total{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\",device=~\"(eth|eno).*\"} > 0) or (irate(node_network_transmit_bytes{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\",device=~\"(eth|eno).*\"} [5m]) and node_network_transmit_bytes{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\",device=~\"(eth|eno).*\"} > 0)",
     "legendFormat": "{{ instance }} {{device}}"
    }
   ]
  },
  {
   "title": "disk time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(rate(node_disk_io_time_seconds_total{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\",device=\"$disk_device\"}[5m])*1000) or rate(node_disk_io_time_ms{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\",device=\"$disk_device\"}[5m])",
     "legendFormat": "{{instance}} / {{device}}"
    }
   ]
  },
  {
   "title": "TCP Connections TIME_WAIT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_tw{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "nf_conntrack count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (node_nf_conntrack_entries{instance=~\"$kafka_broker\",cluster=\"$cluster\"})",
     "target": "node"
    }
   ]
  },
  {
   "title": "File system used %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1- (node_filesystem_avail_bytes{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\",fstype!~\"(tmpfs|rpc_pipefs|debugfs)\"} / node_filesystem_size_bytes{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\"})) or (1- (node_filesystem_avail{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\",fstype!~\"(tmpfs|rpc_pipefs|debugfs)\"} / node_filesystem_size{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\"}))",
     "legendFormat": "{{ instance }} {{ device }}"
    }
   ]
  },
  {
   "title": "Largest topic partition per broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "targets": [
    {
     "expr": "topk(1, kafka_log_Size{cluster=\"$cluster\", instance=~\"$kafka_broker.*\"}) by (instance) > 0",
     "legendFormat": "{{ instance }} {{ topic }} {{ partition }}"
    }
   ]
  },
  {
   "title": "Total Topic Partition Data per Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (instance) (kafka_log_Size{cluster=\"$cluster\", instance=~\"$kafka_broker.*\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_UnderReplicatedPartitions{cluster=\"$cluster\",instance=~\"$kafka_broker.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "ISR Shrinks Per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_ReplicaManager_IsrShrinks_total{cluster=\"$cluster\",instance=~\"$kafka_broker.*\"} [5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Max Replica Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaFetcherManager_MaxLag{cluster=\"$cluster\",instance=~\"$kafka_broker.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Log Flush Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_log_LogFlushStats_LogFlushRateAndTimeMs_Count{cluster=\"$cluster\",instance=~\"$kafka_broker.*\"} [5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Kafka CPU % Utilization",
   "type": "graph",
   "description": "% not idle",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu{cluster=\"$cluster\",mode!=\"idle\",instance=~\"$kafka_broker.*\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\"} or node_memory_Cached{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\"}",
     "legendFormat": "{{ instance }} Cached"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\"} - node_memory_Writeback_bytes{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\"} - node_memory_Cached_bytes{instance=~\"$kafka_broker:.*\"} - node_memory_Buffers_bytes{instance=~\"$kafka_broker:.*\"} - node_memory_MemFree_bytes{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\"}) or (node_memory_MemTotal{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\"} - node_memory_Writeback{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\"} - node_memory_Cached{instance=~\"$kafka_broker:.*\"} - node_memory_Buffers{instance=~\"$kafka_broker:.*\"} - node_memory_MemFree{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\"})",
     "legendFormat": "{{ instance }} Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\"} or node_memory_MemTotal{cluster=\"$cluster\",instance=~\"$kafka_broker:.*\"}",
     "legendFormat": "{{ instance }} Total"
    }
   ]
  },
  {
   "title": "Partition Leaders",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_LeaderCount{cluster=\"$cluster\",instance=~\"$kafka_broker.*\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.ReplicaManager.LeaderCount.Value, 4, 8)"
    },
    {
     "expr": "sum(kafka_server_ReplicaManager_LeaderCount{cluster=\"$cluster\",instance=~\"$kafka_broker.*\"})",
     "legendFormat": "Total Leaders",
     "target": "aliasByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.ReplicaManager.LeaderCount.Value, 4, 8)"
    }
   ]
  },
  {
   "title": "Partitions count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_PartitionCount{cluster=\"$cluster\",instance=~\"$kafka_broker.*\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.ReplicaManager.LeaderCount.Value, 4, 8)"
    }
   ]
  },
  {
   "title": "Brokers acting as Controller",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_ActiveControllerCount_Value{cluster=\"$cluster\",instance=~\"$kafka_broker.*\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.ReplicaManager.LeaderCount.Value, 4, 8)"
    }
   ]
  },
  {
   "title": "Brokers preferred replicas imbalance count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_PreferredReplicaImbalanceCount_Value{cluster=\"$cluster\",instance=~\"$kafka_broker.*\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.ReplicaManager.LeaderCount.Value, 4, 8)"
    }
   ]
  },
  {
   "title": "Offline partition count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_OfflinePartitionsCount_Value{cluster=\"$cluster\",instance=~\"$kafka_broker.*\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.ReplicaManager.LeaderCount.Value, 4, 8)"
    }
   ]
  },
  {
   "title": "G1 Young Generation time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{cluster=\"$cluster\",gc=\"G1 Young Generation\",instance=~\"$kafka_broker.*\"} [5m])",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(derivative(kafka.cluster.$cluster.jvm_memory.$kafka_brokers.sun_management_GarbageCollectorImpl.G1YoungGeneration.CollectionTime.mean), 4)"
    }
   ]
  },
  {
   "title": "G1 Young Generation Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_collection_seconds_count{cluster=\"$cluster\",gc=\"G1 Young Generation\",instance=~\"$kafka_broker.*\"} [5m])",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(derivative(kafka.cluster.$cluster.jvm_memory.$kafka_brokers.sun_management_GarbageCollectorImpl.G1YoungGeneration.CollectionCount.mean), 4)"
    }
   ]
  },
  {
   "title": "G1 Old Generation time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{cluster=\"$cluster\",gc=\"G1 Old Generation\",instance=~\"$kafka_broker.*\"} [5m])",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(derivative(kafka.cluster.$cluster.jvm_memory.$kafka_brokers.sun_management_GarbageCollectorImpl.G1OldGeneration.CollectionTime.mean), 4)"
    }
   ]
  },
  {
   "title": "G1 Old Generation Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_collection_seconds_count{cluster=\"$cluster\",gc=\"G1 Old Generation\",instance=~\"$kafka_broker.*\"} [5m])",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(derivative(kafka.cluster.$cluster.jvm_memory.$kafka_brokers.sun_management_GarbageCollectorImpl.G1OldGeneration.CollectionCount.mean), 4)"
    }
   ]
  },
  {
   "title": "JVM Heap max and used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{cluster=\"$cluster\",area=\"heap\",instance=~\"$kafka_broker.*\"}",
     "legendFormat": "{{ instance }} (used)"
    },
    {
     "expr": "jvm_memory_bytes_max{cluster=\"$cluster\",area=\"heap\",instance=~\"$kafka_broker.*\"}",
     "legendFormat": "{{ instance }} (max)"
    }
   ]
  },
  {
   "title": "JVM NIO Direct vs Mapped areas used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_buffers{cluster=\"$cluster\",instance=~\"$kafka_broker.*\"}",
     "legendFormat": "{{ instance }} {{ pool }}"
    }
   ]
  },
  {
   "title": "JVM NIO Direct vs Mapped used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_bytes{cluster=\"$cluster\",instance=~\"$kafka_broker.*\"}",
     "legendFormat": "{{ instance }} {{ pool }}"
    }
   ]
  }
 ]
}