{
 "title": "Kafka Per Topic",
 "tags": [
  "kafka",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(kafka_server_KafkaServer_BrokerState, cluster)"
   },
   {
    "name": "broker",
    "query": "label_values(kafka_server_KafkaServer_BrokerState{cluster=\"$cluster\"}, instance)"
   },
   {
    "name": "topic",
    "query": "label_values(kafka_server_BrokerTopicMetrics_MessagesIn_total{cluster=\"$cluster\"}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka Messages In by topic (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_MessagesIn_total{cluster=\"$cluster\", instance=~\"$broker.*\", topic=\"$topic\"}[5m])",
     "legendFormat": "{{ instance }}",
     "target": "sortByMaxima(groupByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.BrokerTopicMetrics.MessagesInPerSec.$topic.OneMinuteRate, 9, 'sum'))"
    }
   ]
  },
  {
   "title": "Kafka Messages In by topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_MessagesIn_total{cluster=\"$cluster\", instance=~\"$broker.*\", topic=\"$topic\"}[5m])",
     "legendFormat": "{{ instance }}",
     "target": "sortByMaxima(groupByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.BrokerTopicMetrics.MessagesInPerSec.$topic.OneMinuteRate, 9, 'sum'))"
    }
   ]
  },
  {
   "title": "Kafka Bytes In by topic (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_BytesIn_total{cluster=\"$cluster\", instance=~\"$broker\", topic=\"$topic\"}[5m])",
     "legendFormat": "{{ instance }}",
     "target": "sortByMaxima(groupByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.BrokerTopicMetrics.BytesInPerSec.$topic.OneMinuteRate, 9, 'sum'))"
    }
   ]
  },
  {
   "title": "Kafka Bytes In by topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_BytesIn_total{cluster=\"$cluster\", instance=~\"$broker\", topic=\"$topic\"}[5m])",
     "legendFormat": "{{ instance }}",
     "target": "sortByMaxima(groupByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.BrokerTopicMetrics.BytesInPerSec.$topic.OneMinuteRate, 9, 'sum'))"
    }
   ]
  },
  {
   "title": "Kafka Bytes Out by topic (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_BytesOut_total{cluster=\"$cluster\", instance=~\"$broker\", topic=\"$topic\"}[5m])",
     "legendFormat": "{{ instance }}",
     "target": "sortByMaxima(groupByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.BrokerTopicMetrics.BytesOutPerSec.$topic.OneMinuteRate, 9, 'sum'))"
    }
   ]
  },
  {
   "title": "Kafka Bytes Out by topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_BytesOut_total{cluster=\"$cluster\", instance=~\"$broker\", topic=\"$topic\"}[5m])",
     "legendFormat": "{{ instance }}",
     "target": "sortByMaxima(groupByNode(kafka.cluster.$cluster.kafka.$kafka_brokers.kafka.server.BrokerTopicMetrics.BytesOutPerSec.$topic.OneMinuteRate, 9, 'sum'))"
    }
   ]
  }
 ]
}