{
 "title": "Spark Overview",
 "tags": [
  "spark",
  "application",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "applicationName", "query": "label_values(app_name)" },
   { "name": "jobId", "query": "label_values(exported_job)" },
   {
    "name": "applicationId",
    "query": "label_values(exported_instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Executor HDFS read ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_executor_filesystem_hdfs_read_ops{exported_job=\"$jobId\", exported_instance=\"$applicationId\"}",
     "legendFormat": "{{executor_id}} hdfs read ops"
    },
    {
     "expr": "spark_executor_filesystem_file_read_ops{exported_job=\"$jobId\", exported_instance=\"$applicationId\"}",
     "legendFormat": "{{executor_id}} fs read ops"
    },
    {
     "expr": "spark_executor_filesystem_hdfs_write_ops{exported_job=\"$jobId\", exported_instance=\"$applicationId\"}",
     "legendFormat": "{{executor_id}} hdfs write ops"
    },
    {
     "expr": "spark_executor_filesystem_fs_write_ops{exported_job=\"$jobId\", exported_instance=\"$applicationId\"}",
     "legendFormat": "{{executor_id}} fs write ops"
    },
    {
     "expr": "spark_executor_filesystem_hdfs_largeRead_ops{exported_job=\"$jobId\", exported_instance=\"$applicationId\"}",
     "legendFormat": "{{executor_id}} hdfs large read ops"
    },
    {
     "expr": "spark_executor_filesystem_file_largeRead_ops{exported_job=\"$jobId\", exported_instance=\"$applicationId\"}",
     "legendFormat": "{{executor_id}} fs large read ops"
    }
   ]
  },
  {
   "title": "Executor HDFS writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filesystem_usage{exported_job=\"write_bytes\", fs_type=\"hdfs\", application=\"$application_ID\"}",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "HDFS Read Rate / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(filesystem_usage{exported_job=\"read_bytes\", fs_type=\"hdfs\", application=\"$application_ID\"}[1m]))",
     "legendFormat": "average"
    },
    {
     "expr": "sum(rate(filesystem_usage{exported_job=\"read_bytes\", fs_type=\"hdfs\", application=\"$application_ID\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Driver Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_jvm_heap_usage{exported_instance=\"$applicationId\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "spark_driver_jvm_heap_max{exported_instance=\"$applicationId\"}",
     "legendFormat": "max"
    },
    {
     "expr": "spark_driver_jvm_heap_used{exported_instance=\"$applicationId\"}",
     "legendFormat": "used"
    },
    {
     "expr": "spark_driver_jvm_heap_committed{exported_instance=\"$applicationId\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "Driver JVM Memory Pools",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools{executor_id=\"driver\", application=\"$application_ID\",qty=\"used\"}",
     "legendFormat": "{{mem_type}}"
    }
   ]
  },
  {
   "title": "Executor Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_usage{mem_type=\"heap\", qty=\"usage\", application=\"$application_ID\", executor_id!~\"driver\"} ",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Eden-Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools{executor_id!~\"driver\", application=\"$application_ID\",qty=\"usage\", mem_type=\"PS-Eden-Space\"}",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Old-Gen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools{executor_id!~\"driver\", application=\"$application_ID\",qty=\"usage\", mem_type=\"PS-Old-Gen\"}",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_driver_jvm_total_used{application=\"$application_ID\", qty!~\"maxPool_size\"}) by (qty)",
     "legendFormat": "{{qty}}"
    }
   ]
  }
 ]
}