{
 "title": "Zookeeper",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(org_apache_ZooKeeperService_OutstandingRequests, zookeeper_cluster)"
   },
   {
    "name": "zookeeper_hosts",
    "query": "label_values(org_apache_ZooKeeperService_OutstandingRequests{zookeeper_cluster=\"$cluster\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_ZooKeeperService_NumAliveConnections{zookeeper_cluster=\"$cluster\", instance=~\"$zookeeper_hosts\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.NumAliveConnections, 4, 6)"
    }
   ]
  },
  {
   "title": "Avg Request Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ticks" }
   ],
   "targets": [
    {
     "expr": "org_apache_ZooKeeperService_AvgRequestLatency{zookeeper_cluster=\"$cluster\", instance=~\"$zookeeper_hosts\"}",
     "legendFormat": "{{instance}}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.AvgRequestLatency, 4, 6)"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_ZooKeeperService_OutstandingRequests{zookeeper_cluster=\"$cluster\", instance=~\"$zookeeper_hosts\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    }
   ]
  },
  {
   "title": "Pending session revalidations",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_ZooKeeperService_PendingRevalidationCount{zookeeper_cluster=\"$cluster\", instance=~\"$zookeeper_hosts\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    }
   ]
  },
  {
   "title": "Znodes count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_ZooKeeperService_NodeCount{zookeeper_cluster=\"$cluster\", instance=~\"$zookeeper_hosts\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    }
   ]
  },
  {
   "title": "Watch count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_ZooKeeperService_WatchCount{zookeeper_cluster=\"$cluster\", instance=~\"$zookeeper_hosts\"}",
     "legendFormat": "{{ instance }}",
     "target": "aliasByNode(zookeeper.cluster.$cluster.zookeeper.$zookeeper_hosts.zookeeper.OutstandingRequests, 4, 6)"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{zookeeper_cluster=\"$cluster\", instance=~\"$zookeeper_hosts\"}[5m])",
     "legendFormat": "{{ instance }} {{gc}}",
     "target": "aliasByNode(nonNegativeDerivative(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.sun_management_GarbageCollectorImpl.PSScavenge.CollectionTime.upper), 4)"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{zookeeper_cluster=\"$cluster\", instance=~\"$zookeeper_hosts\"}[5m])",
     "legendFormat": "{{instance}} {{gc}}",
     "target": "aliasByNode(nonNegativeDerivative(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.sun_management_GarbageCollectorImpl.PSMarkSweep.CollectionCount.upper), 4)"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Heap Used vs Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{zookeeper_cluster=\"$cluster\", instance=~\"$zookeeper_hosts\", area=\"heap\"}",
     "legendFormat": "{{instance}} used",
     "target": "aliasByNode(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.memory.HeapMemoryUsage_used.upper, 4, 6)"
    },
    {
     "expr": "jvm_memory_bytes_max{zookeeper_cluster=\"$cluster\", instance=~\"$zookeeper_hosts\", area=\"heap\"}",
     "legendFormat": "{{instance}} max",
     "target": "aliasByNode(zookeeper.cluster.$cluster.jvm_memory.$zookeeper_hosts.memory.HeapMemoryUsage_max.upper, 4, 6)"
    }
   ]
  }
 ]
}