---

jmx_prometheus_javaagent_version: 0.11.0
jmx_prometheus_javaagent_lib_dir: /var/lib/jmx_prometheus_javaagent
jmx_prometheus_javaagent_state: present
ambari_url: http://localhost:8080
ambari_user: raj_ops


jmx_configirations:
- { groups: ["all", "targets"], service: "kafka",     component: "kafka",                type: "kafka-env",     opts: "KAFKA_OPTS",                port: "7071", state: "{{ jmx_prometheus_javaagent_state }}" }
- { groups: ["all", "targets"], service: "zookeeper", component: "zookeeper",            type: "zookeeper-env", opts: "SERVER_JVMFLAGS",           port: "2188", state: "{{ jmx_prometheus_javaagent_state }}" }
- { groups: ["all", "targets"], service: "hdfs",      component: "namenode",             type: "hadoop-env",    opts: "HADOOP_NAMENODE_OPTS",      port: "9102", state: "{{ jmx_prometheus_javaagent_state }}" }
- { groups: ["all", "targets"], service: "hdfs",      component: "datanode",             type: "hadoop-env",    opts: "HADOOP_DATANODE_OPTS",      port: "9103", state: "{{ jmx_prometheus_javaagent_state }}" }
- { groups: ["all", "targets"], service: "hdfs",      component: "journalnode",          type: "hadoop-env",    opts: "HADOOP_JOURNALNODE_OPTS",   port: "9108", state: "{{ jmx_prometheus_javaagent_state }}" }
- { groups: ["all", "targets"], service: "yarn",      component: "resourcemanager",      type: "yarn-env",      opts: "YARN_RESOURCEMANAGER_OPTS", port: "9104", state: "{{ jmx_prometheus_javaagent_state }}" }
- { groups: ["all", "targets"], service: "yarn",      component: "nodemanager",          type: "yarn-env",      opts: "YARN_NODEMANAGER_OPTS",     port: "9105", state: "{{ jmx_prometheus_javaagent_state }}" }
- { groups: ["all", "targets"], service: "hbase",     component: "hmaster",              type: "hbase-env",     opts: "HBASE_MASTER_OPTS",         port: "9106", state: "{{ jmx_prometheus_javaagent_state }}" }
- { groups: ["all", "targets"], service: "hbase",     component: "hregion",              type: "hbase-env",     opts: "HBASE_REGIONSERVER_OPTS",   port: "9107", state: "{{ jmx_prometheus_javaagent_state }}" }

