{
 "title": "Elasticsearch Indexing",
 "tags": [
  "elastic",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(elasticsearch_cluster_health_status,exported_cluster)"
   },
   {
    "name": "server",
    "query": "label_values(elasticsearch_cluster_health_status{exported_cluster=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_nodes{exported_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Shards (primaries)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_active_primary_shards{exported_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Shards (total)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_active_shards{exported_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Docs (total)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs{exported_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "IPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(elasticsearch_indices_indexing_index_total{exported_cluster=~\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Merged segments size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(elasticsearch_indices_merges_total_size_bytes_total{exported_cluster=~\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Average Indexing Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(elasticsearch_indices_indexing_index_time_seconds_total{exported_cluster=~\"$cluster\"}[5m]))*1000/sum(irate(elasticsearch_indices_indexing_index_total{exported_cluster=~\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "Average Query Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds{instance=~\"$server.*\",exported_cluster=~\"$cluster\"}[5m])* 1000 / irate(elasticsearch_indices_search_query_total{instance=~\"$server.*\",exported_cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Average Fetch Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_search_fetch_time_seconds{instance=~\"$server.*\", exported_cluster=~\"$cluster\"}[5m])",
     "legendFormat": "$nodeA"
    },
    {
     "expr": "irate(elasticsearch_indices_search_fetch_time_seconds{instance=~\"$server.*\", exported_cluster=~\"$cluster\"}[5m])* 1000 / irate(elasticsearch_indices_search_fetch_total{instance=~\"$server.*\", exported_cluster=~\"$cluster\"}[5m])",
     "legendFormat": "$nodeB"
    }
   ]
  },
  {
   "title": "Disk Write/Read Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed_total{}[5m]))*60 or sum(irate(node_disk_reads_completed{}[5m]))*60",
     "legendFormat": "reads"
    },
    {
     "expr": "sum(irate(node_disk_writes_completed_total{}[5m]))*60 or sum(irate(node_disk_writes_completed{}[5m]))*60",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_relocating_shards{exported_cluster=~\"$cluster\"})",
     "legendFormat": "eqiad"
    },
    {
     "expr": "avg(elasticsearch_cluster_health_relocating_shards{exported_cluster=~\"$cluster\"})",
     "legendFormat": "codfw"
    }
   ]
  }
 ]
}