{
 "title": "Elasticsearch Memory",
 "tags": [
  "elastic",
  "prometheus"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(elasticsearch_cluster_health_status, exported_cluster)"
   },
   {
    "name": "server",
    "query": "label_values(elasticsearch_cluster_health_status{exported_cluster=~\"$cluster\"}, instance)"
   },
   {
    "name": "top5_fielddata",
    "query": "query_result(topk(5, avg_over_time(elasticsearch_indices_fielddata_memory_size_bytes{exported_cluster=~\"$cluster\"}[${__range_s}s])))"
   },
   {
    "name": "top10_terms",
    "query": "query_result(topk(10, avg_over_time(elasticsearch_indices_segments_terms_memory_in_bytes{exported_cluster=~\"$cluster\"}[${__range_s}s])))"
   },
   {
    "name": "top5_completion",
    "query": "query_result(topk(5, avg_over_time(elasticsearch_indices_completion_size_in_bytes{exported_cluster=~\"$cluster\"}[${__range_s}s])))"
   }
  ]
 },
 "panels": [
  {
   "title": "Terms (completion included)",
   "type": "graph",
   "description": "missing metric",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_segments_terms_memory_in_bytes{exported_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "IndexWriter buffers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_segments_index_writer_memory_in_bytes{exported_cluster=~\"$cluster\"})",
     "legendFormat": "IndexWriter buffers"
    }
   ]
  },
  {
   "title": "Completion Indices",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_completion_size_in_bytes{exported_cluster=~\"$cluster\"})",
     "legendFormat": "Completion Indices"
    }
   ]
  },
  {
   "title": "Fielddata in mem",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_fielddata_memory_size_bytes{cluster=\"elasticsearch\", exported_cluster=~\"$cluster\"})",
     "legendFormat": "Fielddata in mem"
    }
   ]
  },
  {
   "title": "Various",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_segments_norms_memory_in_bytes{exported_cluster=~\"$cluster\"})",
     "legendFormat": "norms"
    },
    {
     "expr": "sum(elasticsearch_indices_segments_stored_fields_memory_in_bytes{exported_cluster=~\"$cluster\"})",
     "legendFormat": "stored fields"
    },
    {
     "expr": "sum(elasticsearch_indices_segments_doc_values_memory_in_bytes{exported_cluster=~\"$cluster\"})",
     "legendFormat": "doc values"
    },
    {
     "expr": "sum(elasticsearch_indices_segments_fixed_bit_set_memory_in_bytes{exported_cluster=~\"$cluster\"})",
     "legendFormat": "fixed bit set"
    }
   ]
  },
  {
   "title": "Top 5 Completion Indices",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, elasticsearch_indices_completion_size_in_bytes{exported_cluster=~\"$cluster\", instance=~\"$top5_completion\"})",
     "legendFormat": "top5",
     "target": "aliasByNode(highestCurrent(servers.elastic1*.elasticsearch.indices.completion.size_in_bytes, 5), 1)"
    },
    {
     "expr": "avg(elasticsearch_indices_completion_size_in_bytes{exported_cluster=~\"$cluster\"})",
     "legendFormat": "avg",
     "target": "alias(averageSeries(servers.elastic1*.elasticsearch.indices.completion.size_in_bytes), 'avg/node')"
    }
   ]
  },
  {
   "title": "Top 5 Fielddata",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_fielddata_memory_size_bytes{instance=~\"$top5_fielddata\",exported_cluster=~\"$cluster\"}",
     "legendFormat": "top5"
    },
    {
     "expr": "avg(elasticsearch_indices_fielddata_memory_size_bytes{exported_cluster=~\"$cluster\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Top 10 Terms",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_terms_memory_in_bytes{instance=~\"$top10_terms\", exported_cluster=~\"$cluster\"}",
     "legendFormat": "top10"
    },
    {
     "expr": "avg(elasticsearch_indices_segments_terms_memory_in_bytes{exported_cluster=~\"$cluster\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "GC Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "min_over_time(elasticsearch_jvm_memory_used_bytes{instance=~\"$server.*\",exported_cluster=~\"$cluster\", area=\"heap\"}[90m])",
     "legendFormat": "min heap"
    },
    {
     "expr": "max_over_time(elasticsearch_jvm_memory_used_bytes{instance=~\"$server.*\", exported_cluster=~\"$cluster\", area=\"heap\"}[90m])",
     "legendFormat": "max heap used"
    },
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{instance=~\"$server.*\",exported_cluster=~\"$cluster\", gc=\"old\"}[3h])*3600",
     "legendFormat": "old gc/hour"
    },
    {
     "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{instance=~\"$server.*\",exported_cluster=~\"$cluster\", gc=\"young\"}[10m])",
     "legendFormat": "new gc/secs"
    }
   ]
  },
  {
   "title": "Disk Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~'$server.*'}[5m]) or irate(node_disk_reads_completed{instance=~'$server'}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~'$server.*'}[5m]) or irate(node_disk_writes_completed{instance=~'$server.*'}[5m])",
     "legendFormat": "{{device}}_writes"
    }
   ]
  }
 ]
}