{
 "title": "Storm - Home",
 "tags": [
  "prometheus",
  "storm"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<h4 align=\"center\">Metrics to see the overall status for the Storm topology. Click on each row title to expand on demand to look at various metrics. </h4>\n<h6 style=\"color:red;\" align=\"center\">This dashboard is managed by Ambari.  You may lose any changes made to this dashboard.  If you want to customize, make your own copy.</h6>\n<h5 align=\"center\">Note: Period ('.') contained topology names are not supported.</h5>"
  },
  {
   "title": "Topologies",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "avg",
     "app": "nimbus",
     "downsampleAggregator": "avg",
     "metric": "Topologies",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Supervisors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "avg",
     "app": "nimbus",
     "downsampleAggregator": "avg",
     "metric": "Supervisors",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Total Executors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "avg",
     "app": "nimbus",
     "downsampleAggregator": "avg",
     "metric": "Total Executors",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Total Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "avg",
     "app": "nimbus",
     "downsampleAggregator": "avg",
     "metric": "Total Tasks",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Free Slots",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "avg",
     "app": "nimbus",
     "downsampleAggregator": "avg",
     "metric": "Free Slots",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Used Slots",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "avg",
     "app": "nimbus",
     "downsampleAggregator": "avg",
     "metric": "Used Slots",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Total Slots",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "avg",
     "app": "nimbus",
     "downsampleAggregator": "avg",
     "metric": "Total Slots",
     "precision": "default",
     "seriesAggregator": "none",
     "transform": "none"
    }
   ]
  }
 ]
}