---
lowercaseOutputLabelNames: true
lowercaseOutputName: false

whitelistObjectNames: ["Hadoop:*"]
rules:
  - pattern: "^Hadoop<service=HBase, name=(\\w+), sub=IPC><>(\\w+)"
    name: "hbase_ipc_$2"
    labels:
      role: "$1"
  - pattern: "^Hadoop<service=HBase, name=(\\w+), sub=Server><>(\\w+)"
    name: "hbase_server_$2"
    labels:
      role: "$1"
  - pattern: "^Hadoop<service=HBase, name=(\\w+), sub=WAL><>(\\w+)"
    name: "hbase_wal_$2"
    labels:
      role: "$1"