---
startDelaySeconds: 0
ssl: false
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
  - 'Hadoop:service=NameNode,name=FSNamesystem'
  - 'Hadoop:service=NameNode,name=NameNodeActivity'
  - 'Hadoop:service=NameNode,name=RpcActivityForPort8020'
blacklistObjectNames:
  - 'Hadoop:service=NameNode,name=RetryCache.NameNodeRetryCache'
  - 'Hadoop:service=NameNode,name=RpcActivity*'
  - 'Hadoop:service=NameNode,name=RpcDetailedActivity*'
  - 'Hadoop:service=NameNode,name=UgiMetrics'
rules:
  - pattern: "^Hadoop<service=(\\w+), name=FSNamesystem><>(\\w+)"
    name: "hadoop_fs_$2"
    labels:
      role: "$1"
  - pattern: "^Hadoop<service=(\\w+), name=NameNodeActivity><>(\\w+)"
    name: "hadoop_activity_$2"
    labels:
      role: "$1"
  - pattern: "^Hadoop<service=(\\w+), name=NameNodeInfo><>(\\w+)"
    name: "hadoop_info_$2"
    labels:
      role: "$1"
  # MetricsSystem
  - pattern: 'Hadoop<service=(.*), name=MetricsSystem, sub=(.*)><>(.*): (\d+)'
    attrNameSnakeCase: true
    name: hadoop_$1_$3
    value: $4
    labels:
      service: HDFS
      role: $1
      kind: 'MetricsSystem'
      sub: $2
    type: GAUGE
  # All NameNode infos
  - pattern: 'Hadoop<service=(.*), name=(.*)><>(.*): (\d+)'
    attrNameSnakeCase: true
    name: hadoop_$1_$3
    value: $4
    labels:
      service: HDFS
      role: $1
      kind: $2
    type: GAUGE