---
elasticsearch_exporter_install_dir: "/var/lib/elasticsearch-exporter"
elasticsearch_exporter_version: "1.1.0rc1"
elasticsearch_exporter_name: "elasticsearch_exporter-{{ elasticsearch_exporter_version }}.linux-amd64"
elasticsearch_exporter_url: "https://github.com/justwatchcom/elasticsearch_exporter/releases/download/v{{ elasticsearch_exporter_version }}/{{ elasticsearch_exporter_name }}.tar.gz"
elasticsearch_exporter_binary: "{{ elasticsearch_exporter_install_dir }}/{{ elasticsearch_exporter_name }}/elasticsearch_exporter"
elasticsearch_exporter_symlink: "{{ elasticsearch_exporter_install_dir }}/elasticsearch_exporter"

elasticsearch_exporter_es_uri: "http://localhost:9200"
elasticsearch_exporter_es_all: "true"
elasticsearch_exporter_es_indices: "true"
elasticsearch_exporter_es_shards: "true"
elasticsearch_exporter_es_timeout: "5s"
elasticsearch_exporter_es_ssl_skip_verify: "true"
elasticsearch_exporter_web_listen_address: ":9114"
elasticsearch_exporter_web_telemetry_path: "/metrics"
# elasticsearch_exporter_es_ca: "/path/to/ca"
# elasticsearch_exporter_es_client-private-key: "/path/to/pk"
# elasticsearch_exporter_es_client-cert: "/path/to/cert"