---
netdata_version: v1.12.2
netdata_install_dir: /usr/local/bin
netdata_installer_options: ""
repo_url: http://10.168.0.45:8089/repository/raw-public/monitoring/prometheus


netdata_system_group: "root"
netdata_system_user: "netdata"