---
- name: copy custom alerting rule files
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/rules/"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0640
    validate: "{{ prometheus_install_dir }}/promtool check rules %s"
  with_fileglob: 
  - alerts/*
  notify:
  - reload prometheus

- name: configure prometheus
  template:
    src: "{{ prometheus_config_file }}"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0640
    validate: "{{ prometheus_install_dir }}/promtool check config %s"
  notify:
    - reload prometheus

- name: configure prometheus static targets
  copy:
    content: |
      #jinja2: lstrip_blocks: True
      {{ item.value | to_nice_yaml(indent=2) }}
    dest: "{{ prometheus_config_dir }}/file_sd/{{ item.key }}.yml"
    force: true
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0640
  with_dict: "{{ prometheus_targets }}"
  when: prometheus_targets != {}

- name: copy prometheus custom static targets
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/file_sd/"
    force: true
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0640
  with_fileglob: "{{ prometheus_static_targets_files }}"
