{
 "title": "HBase - RegionServers",
 "tags": [
  "hbase",
  "ams"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "label": "Components", "query": "hbase" },
   { "name": "hosts", "label": "Hosts", "query": "hosts" }
  ]
 },
 "panels": [
  {
   "title": "Num Regions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num Regions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.regionCount",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Store Files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Store File Size",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.storeFileSize",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Store File Count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.storeFileCount",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Num Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num Total Requests /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.totalRequestCount",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Num Write Requests /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.writeRequestCount",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Num Read Requests /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.readRequestCount",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Num Requests - Get / Scan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num Get Requests /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Num Scan Next Requests /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.ScanNext_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Num Requests - Mutate / Delete",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num Mutate Requests /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Num Delete Requests /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Num Requests - Append / Increment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num Append Requests /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Num Increment Requests /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Num Replay Requests /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "RegionServer Memory Used",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.MemHeapUsedM",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RegionServer Offheap Memory Used",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.MemNonHeapUsedM",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Memstore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memstore Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.memStoreSize",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "BlockCache - Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "BlockCache Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheSize",
       "precision": "default"
      }
     ]
    },
    {
     "title": "BlockCache Free Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheFreeSize",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Num Blocks in Cache",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheCount",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "BlockCache - Hits/Misses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num BlockCache Hits /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheHitCount",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Num BlockCache Misses /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheMissCount",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Num BlockCache Evictions /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheEvictionCount",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "BlockCache Caching Hit Percent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheExpressHitPercent",
       "precision": "default"
      }
     ]
    },
    {
     "title": "BlockCache Hit Percent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheCountHitPercent",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Latencies - Get",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get Latencies - Mean",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_mean",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Get Latencies - Median",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_median",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Get Latencies - 75th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_75th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Get Latencies - 95th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_95th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Get Latencies - 99th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_99th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Get Latencies - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_max",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Latencies - Scan Next",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scan Next Latencies - Mean",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.ScanTime_mean",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Scan Next Latencies - Median",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.ScanTime_median",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Scan Next Latencies - 75th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.ScanTime_75th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Scan Next Latencies - 95th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.ScanTime_95th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Scan Next Latencies - 99th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.ScanTime_99th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Scan Next Latencies - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.ScanTime_max",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Latencies - Mutate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mutate Latencies - Mean",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_mean",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Mutate Latencies - Median",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_median",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Mutate Latencies - 75th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_75th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Mutate Latencies - 95th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_95th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Mutate Latencies - 99th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_99th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Mutate Latencies - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_max",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Latencies - Delete",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delete Latencies - Mean",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_mean",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Delete Latencies - Median",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_median",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Delete Latencies - 75th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_75th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Delete Latencies - 95th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_95th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Delete Latencies - 99th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_99th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Delete Latencies - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_max",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Latencies - Increment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Increment Latencies - Mean",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_mean",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Increment Latencies - Median",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_median",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Increment Latencies - 75th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_75th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Increment Latencies - 95th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_95th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Increment Latencies - 99th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_99th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Increment Latencies - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 106 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_max",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Latencies - Append",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Append Latencies - Mean",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_mean",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Append Latencies - Median",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_median",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Append Latencies - 75th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 114 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_75th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Append Latencies - 95th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 114 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_95th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Append Latencies - 99th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 121 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_99th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Append Latencies - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 121 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_max",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Latencies - Replay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replay Latencies - Mean",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 122 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_mean",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Replay Latencies - Median",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 122 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_median",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Replay Latencies - 75th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 129 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_75th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Replay Latencies - 95th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 129 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_95th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Replay Latencies - 99th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 136 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_99th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Replay Latencies - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 136 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_max",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC - Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num RPC/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 137 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.TotalCallTime_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Num Active Handler Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 144 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.numActiveHandler",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Num Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 144 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.numOpenConnections",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC - Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num RPC Calls in General Queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 145 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.numCallsInGeneralQueue",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Num RPC Calls in Priority Queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 145 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.numCallsInPriorityQueue",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Num RPC Calls in Replication Queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 152 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.numCallsInReplicationQueue",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Total Call Queue Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 152 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.queueSize",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC - Call Queued Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Call Queued Time - Mean",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 153 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.QueueCallTime_mean",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Call Queued Time - Median",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 153 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.QueueCallTime_median",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Call Queued Time - 75th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 160 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.QueueCallTime_75th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Call Queued Time - 95th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 160 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.QueueCallTime_95th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Call Queued Time - 99th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 167 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.QueueCallTime_99th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Call Queued Time - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 167 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.QueueCallTime_max",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC - Call Process Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Call Process Time - Mean",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 168 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.ProcessCallTime_mean",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Call Process Time - Median",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 168 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.ProcessCallTime_median",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Call Process Time - 75th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 175 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.ProcessCallTime_75th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Call Process Time - 95th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 175 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.ProcessCallTime_95th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Call Process Time - 99th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 182 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.ProcessCallTime_99th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Call Process Time - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 182 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.ProcessCallTime_max",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC - Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Received bytes/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 183 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.receivedBytes",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "RPC Sent bytes/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 183 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.sentBytes",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL - Files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num WAL Files",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 184 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.hlogFileCount",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Total WAL File Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 184 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.hlogFileSize",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL - Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAL Num Appends /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 185 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.appendCount",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "WAL Num Sync /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 185 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.SyncTime_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL - Sync Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAL Sync Latencies - Mean",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 186 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.SyncTime_mean",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Sync Latencies - Median",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 186 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.SyncTime_median",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Sync Latencies - 75th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 193 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.SyncTime_75th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Sync Latencies - 95th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 193 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.SyncTime_95th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Sync Latencies - 99th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 200 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.SyncTime_99th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Sync Latencies - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 200 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.SyncTime_max",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL - Append Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAL Append Latencies - Mean",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 201 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.AppendTime_mean",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Append Latencies - Median",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 201 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.AppendTime_median",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Append Latencies - 75th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 208 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.AppendTime_75th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Append Latencies - 95th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 208 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.AppendTime_95th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Append Latencies - 99th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 215 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.AppendTime_99th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Append Latencies - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 215 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.AppendTime_max",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL - Append Sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAL Append Sizes - Mean",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 216 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.AppendSize_mean",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Append Sizes - Median",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 216 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.AppendSize_median",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Append Sizes - 75th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 223 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.AppendSize_75th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Append Sizes - 95th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 223 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.AppendSize_95th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Append Sizes - 99th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 230 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.AppendSize_99th_percentile",
       "precision": "default"
      }
     ]
    },
    {
     "title": "WAL Append Sizes - Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 230 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.AppendSize_max",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Slow Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Operations",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 231 },
     "content": "This row shows operations that take longer than 1 second to execute. These are nicked named \"slow\" operations in the metric system. "
    },
    {
     "title": "WAL Num Slow Append /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 234 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.WAL.slowAppendCount",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Num Slow Gets /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 234 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.slowGetCount",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Num Slow Puts /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 238 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.slowPutCount",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Num Slow Deletes /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 238 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.slowDeleteCount",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Flush / Compaction Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flush Queue Length",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 239 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.flushQueueLength",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Compaction Queue Length",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 239 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.compactionQueueLength",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Split Queue Length",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 239 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.splitQueueLength",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - GC Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 240 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.GcCount",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "GC Count ParNew /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 240 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.GcCountParNew",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "GC Count CMS /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 247 },
     "targets": [
      {
       "aggregator": "max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.GcCountConcurrentMarkSweep",
       "precision": "minutes",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - GC Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Times /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 248 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.GcTimeMillis",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "GC Times ParNew /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 248 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.GcTimeMillisParNew",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "GC Times CMS /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 255 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.GcTimeMillisConcurrentMarkSweep",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Locality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percent Files Local",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 256 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.percentFilesLocal",
       "precision": "default"
      }
     ]
    }
   ]
  }
 ]
}