{
 "title": "HBase - Home",
 "tags": [
  "hbase",
  "ams"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "RegionServers / Regions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Num RegionServers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "max",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "metric": "master.Server.numRegionServers",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Num Dead RegionServers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "max",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "metric": "master.Server.numDeadRegionServers",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Num Regions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "sum",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "metric": "regionserver.Server.regionCount",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Avg Num Regions per RegionServer",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "avg",
     "app": "hbase",
     "downsampleAggregator": "avg",
     "metric": "master.Server.averageLoad",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Num Regions / Stores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num Regions / Stores - Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "alias": "regionCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.regionCount",
       "precision": "default"
      },
      {
       "aggregator": "sum",
       "alias": "storeCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.storeCount",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Store File Size / Count - Total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "alias": "storeFileSize",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.storeFileSize",
       "precision": "default"
      },
      {
       "aggregator": "sum",
       "alias": "storeFileCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.storeFileCount",
       "precision": "default"
      },
      {
       "aggregator": "sum",
       "alias": "storeFileIndexSize",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.storeFileIndexSize",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "staticIndexSize",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.staticIndexSize",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "staticBloomSize",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.staticBloomSize",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Num Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num Requests - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "totalRequestCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.totalRequestCount",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "alias": "readRequestCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.readRequestCount",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "alias": "writeRequestCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.writeRequestCount",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "alias": "rpcCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.TotalCallTime_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Num Request - Breakdown - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "getCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_num_ops",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "alias": "scanNextCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.ScanNext_num_ops",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "alias": "mutateCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_num_ops",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "alias": "deleteCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_num_ops",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "alias": "incrementCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_num_ops",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "alias": "appendCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_num_ops",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "alias": "replayCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "RegionServer Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "RegionServer Memory - Average",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "MemHeapMax",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.MemHeapMaxM",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "MemHeapUsed",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.MemHeapUsedM",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "MemHeapCommitted",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.MemHeapCommittedM",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "MemNonHeapMax",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.MemNonHeapMaxM",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "MemNonHeapUsed",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.MemNonHeapUsedM",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "MemNonHeapCommitted",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.MemNonHeapCommittedM",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RegionServer Offheap Memory - Average",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "MemNonHeapMax",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.MemNonHeapMaxM",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "MemNonHeapUsed",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.MemNonHeapUsedM",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "MemNonHeapCommitted",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.MemNonHeapCommittedM",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory - MemStore / BlockCache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memstore / BlockCache - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "memStoreSize",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.memStoreSize",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "blockCacheSize",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheSize",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "blockCacheFreeSize",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheFreeSize",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Num Blocks in BlockCache - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "alias": "blochCacheCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheCount",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "BlockCache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "BlockCache Hit / Miss /s - Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "alias": "blockCacheHitCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheHitCount",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "sum",
       "alias": "blockCacheMissCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheMissCount",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "sum",
       "alias": "blockCacheEvictionCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheEvictionCount",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "BlockCache Hit Percent - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "blockCacheExpressHitPercent",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheExpressHitPercent",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "blockCacheCountHitPercent",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.blockCacheCountHitPercent",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Latencies - Get / Mutate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get Latencies - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Get_mean",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_mean",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Get_median",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_median",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Get_75th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_75th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Get_95th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_95th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Get_99th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_99th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Get_max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_max",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Get_min",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_min",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Get_num_ops",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Get_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Mutate Latencies - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Mutate_mean",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_mean",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Mutate_median",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_median",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Mutate_75th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_75th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Mutate_95th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_95th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Mutate_99th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_99th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Mutate_max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_max",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Mutate_min",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_min",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Mutate_num_ops",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Mutate_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Latencies - Delete / Increment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delete Latencies - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Delete_mean",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_mean",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Delete_median",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_median",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Delete_75th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_75th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Delete_95th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_95th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Delete_99th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_99th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Delete_max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_max",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Delete_min",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_min",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Delete_num_ops",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Delete_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Increment Latencies - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Increment_mean",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_mean",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Increment_median",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_median",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Increment_75th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_75th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Increment_95th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_95th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Increment_99th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_99th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Increment_max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_max",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Increment_min",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_min",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Increment_num_ops",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Increment_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Latencies - Append / Replay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Append Latencies - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Append_mean",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_mean",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Append_median",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_median",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Append_75th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_75th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Append_95th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_95th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Append_99th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_99th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Append_max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_max",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Append_min",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_min",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Append_num_ops",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Append_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "Replay Latencies - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "Replay_mean",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_mean",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Replay_median",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_median",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Replay_75th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_75th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Replay_95th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_95th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Replay_99th_percentile",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_99th_percentile",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Replay_max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_max",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Replay_min",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_min",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "Replay_num_ops",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.Server.Replay_num_ops",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "RegionServer RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "RegionServer RPC - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "alias": "rpcCount",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "master.Master.TotalCallTime_num_ops",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "alias": "numActiveHandler",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.numActiveHandler",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "numOpenConnections",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.numOpenConnections",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RegionServer RPC Queues - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "numCallsInGeneralQueue",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.numCallsInGeneralQueue",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "numCallsInPriorityQueue",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.numCallsInPriorityQueue",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "numCallsInReplicationQueue",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.numCallsInReplicationQueue",
       "precision": "default"
      },
      {
       "aggregator": "avg",
       "alias": "queueSize",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.queueSize",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "RegionServer RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "RegionServer RPC Throughput - Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "receivedBytes",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.receivedBytes",
       "precision": "default",
       "transform": "rate"
      },
      {
       "aggregator": "avg",
       "alias": "sentBytes",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.sentBytes",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  }
 ]
}