{
 "title": "HBase - Misc",
 "tags": [
  "hbase",
  "ams"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "query": "hbase" },
   { "name": "hosts", "query": "hosts" }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "<h4 align=\"center\">Miscellaneous metrics related to the HBase cluster for troubleshooting and other purposes. Click on each row title to expand on demand to look at various metrics. </h4>\n<h6 style=\"color:red;\" align=\"center\">This dashboard is managed by Ansible.  You may lose any changes made to this dashboard.  If you want to customize, make your own copy.</h6>"
  },
  {
   "title": "Regions In Transition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master - Regions In Transition",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "master.AssignmentManger.ritCount",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Master - Regions In Transition Longer Than Threshold Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "master.AssignmentManger.ritCountOverThreshold",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Regions In Transition Oldest Age",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "master.AssignmentManger.ritOldestAge",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Num Threads - Runnable",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master Num Threads - Runnable",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "aggregator": "max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.Master.JvmMetrics.ThreadsRunnable",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RegionServer Num Threads - Runnable",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "aggregator": "max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.ThreadsRunnable",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Num Threads - Blocked",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master Num Threads - Blocked",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "aggregator": "max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.Master.JvmMetrics.ThreadsBlocked",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RegionServer Num Threads - Blocked",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "aggregator": "max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.ThreadsBlocked",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Num Threads - Waiting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master Num Threads - Waiting",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.Master.JvmMetrics.ThreadsWaiting",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RegionServer Num Threads - Waiting",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.ThreadsWaiting",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Num Threads - Timed Waiting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master Num Threads - Timed Waiting",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "aggregator": "max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.Master.JvmMetrics.ThreadsTimedWaiting",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RegionServer Num Threads - Timed Waiting",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "aggregator": "max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.ThreadsTimedWaiting",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Num Threads - New",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master Num Threads - New",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "aggregator": "max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.Master.JvmMetrics.ThreadsNew",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RegionServer Num Threads - New",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "aggregator": "max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.ThreadsNew",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Num Threads - Terminated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master Num Threads - Terminated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "aggregator": "max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.Master.JvmMetrics.ThreadsTerminated",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RegionServer Num Threads - Terminated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "aggregator": "max",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "jvm.RegionServer.JvmMetrics.ThreadsTerminated",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC Authentication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "RegionServer RPC Authentication Successes /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.authenticationSuccesses",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "RegionServer RPC Authentication Failures /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.authenticationFailures",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC Authorization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "RegionServer RPC Authorization Successes /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.authorizationSuccesses",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "RegionServer RPC Authorization Failures /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.authorizationFailures",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master Exceptions /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "master.Master.exceptions",
       "precision": "default",
       "transform": "rate"
      }
     ]
    },
    {
     "title": "RegionServers Exceptions /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "aggregator": "avg",
       "app": "hbase",
       "downsampleAggregator": "avg",
       "metric": "regionserver.RegionServer.exceptions",
       "precision": "default",
       "transform": "rate"
      }
     ]
    }
   ]
  }
 ]
}