{
 "title": "Host overview",
 "tags": [
  "system",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(up{instance=~\"$server.*\"}, cluster)"
   },
   {
    "name": "server",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu{mode!=\"idle\",instance=~\"$server:.*\"}[5m])) / scalar(count(node_cpu{mode=\"idle\",instance=~\"$server:.*\"}))",
     "legendFormat": "{{mode}} "
    }
   ]
  },
  {
   "title": "CPU: saturation (load avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.*\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$server:.*\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$server:.*\"}",
     "legendFormat": "load 15m"
    },
    {
     "expr": "sum(count(node_cpu{job=\"node\",mode=\"idle\",instance=~\"$server:.*\"}) by (cpu))",
     "legendFormat": "CPUs"
    }
   ]
  },
  {
   "title": "Memory: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server:.*\"} or node_memory_MemTotal{instance=~\"$server:.*\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$server:.*\"} or node_memory_Cached{instance=~\"$server:.*\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$server:.*\"} - node_memory_Writeback_bytes{instance=~\"$server:.*\"} - node_memory_Cached_bytes{instance=~\"$server:.*\"} - node_memory_Buffers_bytes{instance=~\"$server:.*\"} - node_memory_MemFree_bytes{instance=~\"$server:.*\"}) or (node_memory_MemTotal{instance=~\"$server:.*\"} - node_memory_Writeback{instance=~\"$server:.*\"} - node_memory_Cached{instance=~\"$server:.*\"} - node_memory_Buffers{instance=~\"$server:.*\"} - node_memory_MemFree{instance=~\"$server:.*\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory: saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "pages/swpin"
    },
    {
     "expr": "rate(node_vmstat_pswpout{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "pages/swpout"
    },
    {
     "expr": "rate(node_vmstat_allocstall_normal{instance=~\"$server:.*\"}[5m]) + rate(node_vmstat_allocstall_dma32{instance=~\"$server:.*\"}[5m]) + rate(node_vmstat_allocstall_dma{instance=~\"$server:.*\"}[5m]) + rate(node_vmstat_allocstall_movable{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "allocstalls"
    }
   ]
  },
  {
   "title": "Network: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m]) > 0) or sum(irate(node_network_receive_bytes{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m]) > 0)",
     "legendFormat": "rx/bytes"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m]) > 0) or sum(irate(node_network_transmit_bytes{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m]) > 0)",
     "legendFormat": "tx/bytes"
    }
   ]
  },
  {
   "title": "Network: errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "(irate(node_network_transmit_drop_total{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m]) + irate(node_network_receive_drop_total{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m])) or (irate(node_network_transmit_drop{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m]) + irate(node_network_receive_drop{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m]))",
     "legendFormat": "drop/{{device}}"
    },
    {
     "expr": "(irate(node_network_transmit_errs_total{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m]) + irate(node_network_receive_errs_total{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m])) or (irate(node_network_transmit_errs{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m]) + irate(node_network_receive_errs{instance=~\"$server.*\",device=~\"(eth|en[0-9a-z]+)[0-9]*\"}[5m]))",
     "legendFormat": "err/{{device}}"
    }
   ]
  },
  {
   "title": "Disk: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$server:.*\",device=~\"[vs]d[a-z]+\"}[5m]) or (irate(node_disk_io_time_ms{instance=~\"$server:.*\",device=~\"[vs]d[a-z]+\"}[5m]) / 1000)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk: saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now{instance=~\"$server.*\",device=~\"[vs]d[a-z]+\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "node_md_is_active{instance=~\"$server:.*\"} < 1",
     "legendFormat": "md_inactive/{{device}}"
    }
   ]
  },
  {
   "title": "Socket: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$server:.*\"}",
     "legendFormat": "tcp/timewait"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~\"$server:.*\"}",
     "legendFormat": "udp/inuse"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~\"$server:.*\"}",
     "legendFormat": "tcp/inuse"
    }
   ]
  },
  {
   "title": "Socket: errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_InErrs{instance=~\"$server.*\"}[5m])",
     "legendFormat": "tcp/inerrs"
    },
    {
     "expr": "rate(node_netstat_Tcp_AttemptFails{instance=~\"$server.*\"}[5m])",
     "legendFormat": "tcp/attemptfails"
    },
    {
     "expr": "rate(node_netstat_Udp_RcvbufErrors{instance=~\"$server.*\"}[5m]) + rate(node_netstat_Udp_SndbufErrors{instance=~\"$server.*\"}[5m])",
     "legendFormat": "udp/buferr"
    },
    {
     "expr": "rate(node_netstat_Udp_InErrors{instance=~\"$server.*\"}[5m])",
     "legendFormat": "udp/inerrs"
    },
    {
     "expr": "rate(node_netstat_Icmp_InErrors{instance=~\"$server.*\"}[5m]) + rate(node_netstat_Icmp_OutErrors{instance=~\"$server.*\"}[5m])",
     "legendFormat": "icmp/errs"
    }
   ]
  },
  {
   "title": "filesystem: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1- (node_filesystem_avail_bytes{instance=~\"$server:.*\",fstype!~\"(tmpfs|rpc_pipefs|debugfs)\"} / node_filesystem_size_bytes{instance=~\"$server:.*\"})) or (1- (node_filesystem_avail{instance=~\"$server:.*\",fstype!~\"(tmpfs|rpc_pipefs|debugfs)\"} / node_filesystem_size{instance=~\"$server:.*\"}))",
     "legendFormat": "{{mountpoint}} (bytes, {{fstype}})"
    },
    {
     "expr": "1- (node_filesystem_files_free{instance=~\"$server:.*\",fstype!~\"(tmpfs|rpc_pipefs|debugfs)\"} / node_filesystem_files{instance=~\"$server:.*\"})",
     "legendFormat": "{{mountpoint}} (inodes, {{fstype}})"
    }
   ]
  },
  {
   "title": "misc: errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_edac_uncorrectable_errors_total{instance=~\"$server.*\"}[4d]))",
     "legendFormat": "edac uncorrectable (4d)",
     "target": "isNonNull()"
    },
    {
     "expr": "node_textfile_scrape_error{instance=~\"$server.*\"} > 0",
     "legendFormat": "textfile scrape error",
     "target": "isNonNull()"
    },
    {
     "expr": "sum(rate(node_edac_correctable_errors_total{instance=~\"$server.*\"}[4d]))",
     "legendFormat": "edac correctable (4d)",
     "target": "isNonNull()"
    },
    {
     "expr": "node_filesystem_device_error{instance=~\"$server.*\"} > 0",
     "legendFormat": "FS error ({{mountpoint}})",
     "target": "isNonNull()"
    },
    {
     "expr": "sum(rate(edac_events{hostname=\"$server\"}[4d]))",
     "legendFormat": "edac syslog lines (4d)"
    }
   ]
  },
  {
   "title": "misc: utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (node_filefd_allocated{instance=~\"$server.*\"} / node_filefd_maximum{instance=~\"$server.*\"})",
     "legendFormat": "fd usage %",
     "target": "isNonNull()"
    },
    {
     "expr": "node_procs_running{instance=~\"$server.*\"}",
     "legendFormat": "procs running",
     "target": "isNonNull()"
    },
    {
     "expr": "100 * (node_nf_conntrack_entries{instance=~\"$server.*\"} / node_nf_conntrack_entries_limit{instance=~\"$server.*\"})",
     "legendFormat": "conntrack usage %",
     "target": "isNonNull()"
    },
    { "expr": "node_", "legendFormat": "interrupts", "target": "isNonNull()" }
   ]
  },
  {
   "title": "misc: saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_blocked{instance=~\"$server.*\"}",
     "legendFormat": "procs blocked",
     "target": "isNonNull()"
    },
    {
     "expr": "node_entropy_available_bits{instance=~\"$server.*\"}",
     "legendFormat": "entropy bytes available",
     "target": "isNonNull()"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~\"$server:.*\"} * ignoring(label) group_left(label) node_hwmon_sensor_label{instance=~\"$server:.*\"}\r\n",
     "legendFormat": "{{chip}} {{label}}"
    }
   ]
  },
  {
   "title": "CPU thermal throttling: saturation",
   "type": "graph",
   "description": "Number of CPU thermal throttling events per second, across all CPUs.\n\nShould always be 0 (or \"no data points\") in a healthy machine.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cpu_throttled{hostname=\"$server\"}[5m])"
    }
   ]
  }
 ]
}