{
 "title": "Network Performances2",
 "tags": [
  "system",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "TCP/UDP input errors > 1% per site:cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cluster:node_netstat_Tcp_Input_Errors:percent5m > 0.1",
     "legendFormat": "TCP {{ site }}:{{ cluster }}"
    },
    {
     "expr": "cluster:node_netstat_Udp_Input_Errors:percent5m > 0.1",
     "legendFormat": "UDP {{ site }}:{{ cluster }}"
    }
   ]
  },
  {
   "title": "TCP retransmits > 1% per site:cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cluster:node_netstat_Tcp_RetransSegs:rate5m * 100 / cluster:node_netstat_Tcp_OutSegs:rate5m > 1",
     "legendFormat": "{{ site }}:{{ cluster }}"
    }
   ]
  },
  {
   "title": "IP errors > 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "cluster:node_netstat_IpExt_InCsumErrors:rate5m > 1",
     "legendFormat": "IN checksum {{ site }}:{{ cluster }}"
    },
    {
     "expr": "cluster:node_netstat_Ip_InAddrErrors:rate5m > 1",
     "legendFormat": "IN addr {{ site }}:{{ cluster }}"
    },
    {
     "expr": "cluster:node_netstat_Ip_InDiscards:rate5m > 1",
     "legendFormat": "IN discards {{ site }}:{{ cluster }}"
    },
    {
     "expr": "cluster:node_netstat_Ip_InHdrErrors:rate5m > 1",
     "legendFormat": "IN header {{ site }}:{{ cluster }}"
    },
    {
     "expr": "cluster:node_netstat_Ip_OutDiscards:rate5m > 1",
     "legendFormat": "OUT discards {{ site }}:{{ cluster }}"
    },
    {
     "expr": "cluster:node_netstat_Ip_OutNoRoutes:rate5m > 1",
     "legendFormat": "OUT no routes {{ site }}:{{ cluster }}"
    },
    {
     "expr": "cluster:node_netstat_Ip_ReasmFails:rate5m > 1",
     "legendFormat": "ReasmFails {{ site }}:{{ cluster }}"
    },
    {
     "expr": "cluster:node_netstat_Ip_ReasmTimeout:rate5m > 1",
     "legendFormat": "ReasmTimeout {{ site }}:{{ cluster }}"
    }
   ]
  },
  {
   "title": "ICMP errors > 10 per site:cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "cluster:netstat_Icmp_InCsumErrors:rate5m > 10",
     "legendFormat": "Checksum {{ site }}:{{ cluster }}"
    },
    {
     "expr": "cluster:netstat_Icmp_InErrors:rate5m > 10",
     "legendFormat": "IN Errors {{ site }}:{{ cluster }}"
    },
    {
     "expr": "cluster:netstat_Icmp_InTimeExcds:rate5m > 10",
     "legendFormat": "IN Time exceeded {{ site }}:{{ cluster }}"
    },
    {
     "expr": "cluster:netstat_Icmp_OutDestUnreachs:rate5m > 10",
     "legendFormat": "OUT Dest Unreach {{ site }}:{{ cluster }}"
    },
    {
     "expr": "cluster:netstat_Icmp_OutErrors:rate5m > 10",
     "legendFormat": "OUT Errors {{ site }}:{{ cluster }}"
    }
   ]
  }
 ]
}