{
 "title": "Network performances",
 "tags": [
  "system",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(up{instance=~\"$server.*\"}, cluster)"
   },
   {
    "name": "server",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Segments/s" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "TCP Outbound"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "UDP outbound"
    },
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "UDP inbound"
    }
   ]
  },
  {
   "title": "ICMP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Datagrams/s" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Icmp_InDestUnreachs{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "Icmp_InDestUnreachs"
    },
    {
     "expr": "irate(node_netstat_Icmp_InErrors{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "Icmp_InErrors"
    },
    {
     "expr": "irate(node_netstat_Icmp_InAddrMasks{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "Icmp_InAddrMasks"
    },
    {
     "expr": "irate(node_netstat_Icmp_InParmProbs{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "Icmp_InParmProbs"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutTimestampReps{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "Icmp_OutTimestampReps"
    },
    {
     "expr": "irate(node_netstat_Icmp_InRedirects{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "Icmp_InRedirects"
    },
    {
     "expr": "irate(node_netstat_Icmp_InTimeExcds{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "Icmp_InTimeExcds"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutDestUnreachs{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "Icmp_OutDestUnreachs"
    },
    {
     "expr": "irate(node_netstat_Icmp_OutTimeExcds{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "Icmp_OutTimeExcds"
    },
    {
     "expr": "irate(node_netstat_Icmp_InCsumErrors{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "Icmp_InCsumErrors"
    }
   ]
  },
  {
   "title": "UDP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Datagrams/s" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "udp_inerrors"
    },
    {
     "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "udp_rcvbuferror"
    },
    {
     "expr": "irate(node_netstat_Udp_SndbufErrors{instance=~\"$server\"}[5m])",
     "legendFormat": "udp_sndbuferror"
    }
   ]
  },
  {
   "title": "TCP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Segments/s" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "TCP SYN Retransmits"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "TCP Retransmits"
    },
    {
     "expr": "irate(node_netstat_Tcp_InCsumErrors{instance=~\"$server:.*\"}[5m])",
     "legendFormat": "TCP Inbound checksum errors"
    }
   ]
  },
  {
   "title": "TCP retransmits %",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(10, node_netstat_Tcp_RetransSegs *100 / node_netstat_Tcp_OutSegs  )",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "ICMP inbound errors",
   "type": "table",
   "description": "Doesn't include node_netstat_Icmp_InErrors",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "topk(10, ( node_netstat_Icmp_InCsumErrors + node_netstat_Icmp_InTimeExcds + node_netstat_Icmp_InRedirects + node_netstat_Icmp_InParmProbs + node_netstat_Icmp_InAddrMasks + node_netstat_Icmp_InDestUnreachs )  * 100 / node_netstat_Icmp_InMsgs )",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}