{
 "title": "YARN - TimelineServer",
 "tags": [
  "yarn",
  "ams"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Data Reads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Timeline Entity Data Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "app": "applicationhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "yarn.TimelineDataManagerMetrics.GetEntitiesTotal",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Timeline Entity Data Read time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "app": "applicationhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "yarn.TimelineDataManagerMetrics.GetEntitiesTimeAvgTime",
     "precision": "default"
    }
   ]
  },
  { "title": "Data Writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Timeline Entity Data Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "app": "applicationhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "yarn.TimelineDataManagerMetrics.PostEntitiesTotal",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Timeline Entity Data Write Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "app": "applicationhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "yarn.TimelineDataManagerMetrics.PostEntitiesTimeAvgTime",
     "precision": "default"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "GC Count",
     "app": "applicationhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.GcCount",
     "precision": "default"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "GC Time",
     "app": "applicationhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.GcTimeMillis",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Max Heap",
     "app": "applicationhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.MemHeapMaxM",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "Heap Used",
     "app": "applicationhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.MemHeapUsedM",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "Heap Committed",
     "app": "applicationhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.MemHeapCommittedM",
     "precision": "default"
    }
   ]
  },
  {
   "title": "NonHeap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "NonHeap Committed",
     "app": "applicationhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.MemNonHeapCommittedM",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "NonHeap Used",
     "app": "applicationhistoryserver",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.MemNonHeapUsedM",
     "precision": "default"
    }
   ]
  }
 ]
}