{
 "title": "YARN - NodeManagers",
 "tags": [
  "yarn",
  "ams"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "query": "nodemanager" },
   { "name": "hosts", "query": "hosts" }
  ]
 },
 "panels": [
  {
   "title": "Num Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Running",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Containers Running",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.ContainersRunning",
       "precision": "default",
       "qmetric": "resourcemanager",
       "queue": "yarn.NodeManagerMetrics.ContainersRunning"
      }
     ]
    },
    {
     "title": "Containers Failed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Containers Failed",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.ContainersFailed",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Containers Killed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Containers Killed",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.ContainersKilled",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Containers Completed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Containers Completed",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.ContainersCompleted",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Available",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Memory Available",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.AvailableGB",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Used Memory",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.AllocatedGB",
       "precision": "default",
       "qmetric": "resourcemanager",
       "queue": "yarn.NodeManagerMetrics.AllocatedGB"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Utilization for Good Log Dirs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Disk Utilization for Good Log Dirs",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.GoodLogDirsDiskUtilizationPerc",
       "precision": "default",
       "qmetric": "resourcemanager",
       "queue": "yarn.NodeManagerMetrics.GoodLogDirsDiskUtilizationPerc"
      }
     ]
    },
    {
     "title": "Disk Utilization for Good Local Dirs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "GoodLocalDirsDiskUtilization",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.GoodLocalDirsDiskUtilizationPerc",
       "precision": "default"
      }
     ]
    },
    {
     "title": "Bad Log Dirs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Bad Log Dirs",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.BadLogDirs",
       "precision": "default",
       "qmetric": "resourcemanager",
       "queue": "yarn.NodeManagerMetrics.BadLogDirs"
      }
     ]
    },
    {
     "title": "Bad Local Dirs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Bad Local Dirs",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.BadLocalDirs",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Avg Container Launch Delay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Container Launch Delay",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Avg Container Launch Delay",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.NodeManagerMetrics.ContainerLaunchDurationAvgTime",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Avg Processing Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC Avg Processing Time",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.RpcProcessingTimeAvgTime",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Avg Queue Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC Avg Queue Time",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.RpcQueueTimeAvgTime",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Call Queue Length",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC Call Queue Length",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.CallQueueLength",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Slow Calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC Slow Calls",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.RpcSlowCalls",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Mem Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Max HeapMem",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapMaxM",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "Used HeapMem",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapUsedM",
       "precision": "default"
      }
     ]
    },
    {
     "title": "NonHeap Mem Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "NonHeap Mem Used",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemNonHeapUsedM",
       "precision": "default"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "GC Count",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.GcCount",
       "precision": "minutes"
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "aggregator": "avg",
       "alias": "GC Time",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.GcTimeMillis",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "LOG4J Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "LOG ERROR",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "LOG Error",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.LogError",
       "precision": "default"
      }
     ]
    },
    {
     "title": "LOG FATAL",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "LOG FATAL",
       "app": "nodemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.LogFatal",
       "precision": "default"
      }
     ]
    }
   ]
  }
 ]
}