{
 "title": "YARN - ResourceManager",
 "tags": [
  "yarn",
  "ams"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "components", "query": "resourcemanager" },
   { "name": "hosts", "query": "hosts" }
  ]
 },
 "panels": [
  {
   "title": "RPC Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Avg Processing / Queue Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC Avg Processing Time",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.RpcProcessingTimeAvgTime",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "RPC Avg Queue Time",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.RpcQueueTimeAvgTime",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Call Queue Length",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC CallQueue Length",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.CallQueueLength",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Slow calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC Slow Calls",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.RpcSlowCalls",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Mem Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Max HeapMem",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapMaxM",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "Used HeapMem",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapUsedM",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "Committed HeapMem",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemHeapCommittedM",
       "precision": "default"
      }
     ]
    },
    {
     "title": "NonHeap Mem Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Used NonHeapMem",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemNonHeapUsedM",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "Committed NonHeapMem",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.MemNonHeapCommittedM",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "GC Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "GC Count",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.GcCount",
       "precision": "default"
      }
     ]
    },
    {
     "title": "GcTime",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "GC Time",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.GcTimeMillis",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Log Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Error/ Fatal",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Log Errors",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.LogError",
       "precision": "default"
      },
      {
       "aggregator": "max",
       "alias": "Log Fatal",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "jvm.JvmMetrics.LogFatal",
       "precision": "default"
      }
     ]
    }
   ]
  },
  {
   "title": "Authorization & Authentication Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Authorization Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC Authorization Failures",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.RpcAuthorizationFailures",
       "precision": "default"
      }
     ]
    },
    {
     "title": "RPC Authentication Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "RPC Authentication Failures",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "rpc.rpc.RpcAuthenticationFailures",
       "precision": "default"
      }
     ]
    }
   ]
  }
 ]
}