{
 "title": "YARN - Home",
 "tags": [
  "yarn",
  "ams"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "aggregator": "max",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.ClusterMetrics.NumActiveNMs",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Cluster Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "max",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AvailableMB",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Running apps",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "max",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsRunning",
     "precision": "default"
    }
   ]
  },
  {
   "title": "ResourceManager Heap",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "max",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "jvm.JvmMetrics.MemHeapUsedM",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Num Active NMs",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.ClusterMetrics.NumActiveNMs",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "Num Unhealthy NMs",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.ClusterMetrics.NumUnhealthyNMs",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "Num Lost NMs",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.ClusterMetrics.NumLostNMs",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Apps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Apps Running",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsRunning",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "Apps Pending",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsPending",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "Apps Failed",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsFailed",
     "precision": "default"
    },
    {
     "aggregator": "max",
     "alias": "Apps Complete",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AppsCompleted",
     "precision": "default"
    }
   ]
  },
  {
   "title": "Cluster Memory Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Cluster Memory Available",
     "app": "resourcemanager",
     "downsampleAggregator": "avg",
     "metric": "yarn.QueueMetrics.Queue=root.AvailableMB",
     "precision": "default"
    }
   ]
  }
 ]
}