{
 "title": "YARN - Queues",
 "tags": [
  "yarn",
  "ams"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "queue", "query": "yarnqueues" }
  ]
 },
 "panels": [
  {
   "title": "Num Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apps Running",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Apps Running",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AppsRunning",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AppsRunning"
      }
     ]
    },
    {
     "title": "Apps Pending",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Apps Pending",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AppsPending",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AppsPending"
      }
     ]
    },
    {
     "title": "Apps Completed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Apps Completed",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AppsCompleted",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AppsCompleted"
      }
     ]
    },
    {
     "title": "Apps Failed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Apps Failed",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AppsFailed",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AppsFailed"
      }
     ]
    },
    {
     "title": "Apps Killed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Apps Killed",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AppsKilled",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AppsKilled"
      }
     ]
    },
    {
     "title": "Apps Submitted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "max",
       "alias": "Apps Submitted",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AppsSubmitted",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AppsSubmitted"
      }
     ]
    }
   ]
  },
  {
   "title": "Num Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Running",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "aggregator": "max",
       "alias": "Containers Running",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AllocatedContainers",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AllocatedContainers"
      }
     ]
    },
    {
     "title": "Containers Pending",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "aggregator": "max",
       "alias": "Pending Containers",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.PendingContainers",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.PendingContainers"
      }
     ]
    },
    {
     "title": "Containers Reserved",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "aggregator": "max",
       "alias": "Containers Reserved",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.default.ReservedContainers",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.default.ReservedContainers"
      }
     ]
    },
    {
     "title": "Total Containers Allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "aggregator": "max",
       "alias": "Total Containers Allocated",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AggregateContainersAllocated",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AggregateContainersAllocated"
      }
     ]
    },
    {
     "title": "Total Node Local Containers Allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "targets": [
      {
       "aggregator": "max",
       "alias": "Node Local Containers Allocated",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AggregateNodeLocalContainersAllocated",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AggregateNodeLocalContainersAllocated"
      }
     ]
    },
    {
     "title": "Total Rack Local Containers Allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "targets": [
      {
       "aggregator": "max",
       "alias": "Rack Local Containers Allocated",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AggregateRackLocalContainersAllocated",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AggregateRackLocalContainersAllocated"
      }
     ]
    },
    {
     "title": "Total OffSwitch Containers Allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "targets": [
      {
       "aggregator": "max",
       "alias": "OffSwitch Containers Allocated",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AggregateOffSwitchContainersAllocated",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AggregateOffSwitchContainersAllocated"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocated Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "aggregator": "max",
       "alias": "Allocated Memory",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AllocatedMB",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AllocatedMB"
      }
     ]
    },
    {
     "title": "Pending Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "aggregator": "max",
       "alias": "Pending Memory",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.PendingMB",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.PendingMB"
      }
     ]
    },
    {
     "title": "Available Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "aggregator": "max",
       "alias": "Available Memory",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AvailableMB",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AvailableMB"
      }
     ]
    },
    {
     "title": "Reserved Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "aggregator": "max",
       "alias": "Reserved Memory",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.default.ReservedMB",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.default.ReservedMB"
      }
     ]
    },
    {
     "title": "Memory used by AM",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "aggregator": "max",
       "alias": "Max AM Mem",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AMResourceLimitMB",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AMResourceLimitMB"
      },
      {
       "aggregator": "max",
       "alias": "Used AM Mem",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.UsedAMResourceMB",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.UsedAMResourceMB"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Allocation Delay",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg AM Container Allocation Delay",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "aggregator": "max",
       "alias": "Avg AM Container Allocation Delay",
       "app": "resourcemanager",
       "downsampleAggregator": "avg",
       "metric": "yarn.QueueMetrics.Queue=root.AppAttemptFirstContainerAllocationDelayAvgTime",
       "precision": "default",
       "qmetric": "root.default",
       "queue": "yarn.QueueMetrics.Queue=root.default.AppAttemptFirstContainerAllocationDelayAvgTime"
      }
     ]
    }
   ]
  }
 ]
}