{
 "title": "Yarn Overview",
 "tags": [
  "yarn",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(Hadoop_NameNode_FilesTotal, cluster)"
   },
   {
    "name": "server",
    "query": "label_values(Hadoop_NameNode_FilesTotal{cluster=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Yarn Resource Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource Manager Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{job=\"resourcemanager\", instance=~\"$server.*\", area=\"heap\", cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }} used",
       "target": "aliasByNode(Hadoop.ResourceManager.*.Hadoop.ResourceManager.JvmMetrics.MemHeapUsedM.upper, 2)"
      },
      {
       "expr": "jvm_memory_bytes_max{instance=~\"$server.*\", area=\"heap\", cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }} max"
      }
     ]
    },
    {
     "title": "Resource Manager GC Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_sum{job=\"resourcemanager\", instance=~\"$server.*\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{ instance }} {{ gc }}",
       "target": "aliasByNode(nonNegativeDerivative(Hadoop.ResourceManager.*.Hadoop.ResourceManager.JvmMetrics.GcTimeMillisPSScavenge.upper), 2)"
      }
     ]
    },
    {
     "title": "Resource Manager GC Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_count{job=\"resourcemanager\", instance=~\"$server.*\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{ instance }} {{ gc }}",
       "target": "aliasByNode(nonNegativeDerivative(Hadoop.ResourceManager.*.Hadoop.ResourceManager.JvmMetrics.GcCountPSMarkSweep.upper), 2)"
      }
     ]
    },
    {
     "title": "Node Managers statuses",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_NumActiveNMs{cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }} Active",
       "target": "aliasByNode(Hadoop.ResourceManager.*.Hadoop.ResourceManager.ClusterMetrics.*.upper, 2, 6)"
      },
      {
       "expr": "Hadoop_ResourceManager_NumUnhealthyNMs{cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }} Unhealthy",
       "target": "aliasByNode(Hadoop.ResourceManager.*.Hadoop.ResourceManager.ClusterMetrics.*.upper, 2, 6)"
      }
     ]
    },
    {
     "title": "Open connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_NumOpenConnections{cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }} {{ name }}"
      }
     ]
    },
    {
     "title": "Call queue lenghts to port 803*",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_CallQueueLength{cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }} {{ name }}"
      }
     ]
    },
    {
     "title": "Number of RPC calls",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(Hadoop_ResourceManager_RpcQueueTimeNumOps{cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{ instance }} {{ name }}"
      }
     ]
    },
    {
     "title": "Average Processing time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_RpcProcessingTimeAvgTime{cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }} {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Yarn Node Managers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Manager running containers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "Hadoop_NodeManager_ContainersRunning{cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }}",
       "target": "sumSeries(Hadoop.NodeManager.*.Hadoop.NodeManager.NodeManagerMetrics.ContainersRunning.upper)"
      }
     ]
    },
    {
     "title": "Node Manager failed/killed containers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(Hadoop_NodeManager_ContainersKilled{cluster=\"$cluster\"}[5m]))",
       "legendFormat": "Killed",
       "target": "alias(perSecond(sumSeries(Hadoop.NodeManager.*.Hadoop.NodeManager.NodeManagerMetrics.ContainersFailed.upper)), 'failed')"
      },
      {
       "expr": "sum(irate(Hadoop_NodeManager_ContainersFailed{cluster=\"$cluster\"}[5m]))",
       "legendFormat": "Failed",
       "target": "alias(perSecond(sumSeries(Hadoop.NodeManager.*.Hadoop.NodeManager.NodeManagerMetrics.ContainersKilled.upper)), 'killed')"
      }
     ]
    },
    {
     "title": "Node Manager GB allocated",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "expr": "Hadoop_NodeManager_AllocatedGB{cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }}",
       "target": "aliasByNode(Hadoop.NodeManager.*.Hadoop.NodeManager.NodeManagerMetrics.AllocatedGB.upper, 2)"
      }
     ]
    },
    {
     "title": "Node Manager containers allocated",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "Hadoop_NodeManager_AllocatedContainers{cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }}",
       "target": "aliasByNode(Hadoop.NodeManager.*.Hadoop.NodeManager.NodeManagerMetrics.AllocatedContainers.upper, 2)"
      }
     ]
    },
    {
     "title": "Node Managers Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{job=\"resourcemanager\", instance=~\"$server.*\", area=\"heap\", cluster=\"$cluster\"}",
       "legendFormat": "{{ instance }} used",
       "target": "aliasByNode(Hadoop.NodeManager.*.Hadoop.NodeManager.JvmMetrics.MemHeapUsedM.upper, 2)"
      },
      {
       "expr": "max(jvm_memory_bytes_max{instance=~\".*:8141\", area=\"heap\", hadoop_cluster=\"$hadoop_cluster\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Node Manager GC Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_sum{job=\"resourcemanager\", instance=~\"$server.*\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{ instance }} {{ gc }}",
       "target": "aliasByNode(nonNegativeDerivative(Hadoop.NodeManager.*.Hadoop.NodeManager.JvmMetrics.GcCountPSScavenge.upper), 2)"
      }
     ]
    },
    {
     "title": "Node Manager GC Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_count{job=\"resourcemanager\", instance=~\"$server.*\", cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{ instance }} {{ gc }}",
       "target": "aliasByNode(nonNegativeDerivative(Hadoop.NodeManager.*.Hadoop.NodeManager.JvmMetrics.GcCountPSMarkSweep.upper), 2)"
      }
     ]
    }
   ]
  }
 ]
}